local _, TFG = ...

TFG.WEAPON_SKILLS_VANILLA = {
    ["druid"] = {
        {
            ["id"] = 199,
            ["name"] = "Two-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_04",
        },
        {
            ["id"] = 198,
            ["name"] = "One-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_01",
        },
        {
            ["id"] = 15590,
            ["name"] = "Fist Weapons",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_gauntlets_04",
        },
        {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        }
    },
    ["hunter"] = {
        {
            ["id"] = 674,
            ["name"] = "Dual Wield",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_dualwield",
        },
        {
            ["id"] = 200,
            ["name"] = "Polearms",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_spear_06",
        },
        {
            ["id"] = 197,
            ["name"] = "Two-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_04",
        },
        {
            ["id"] = 15590,
            ["name"] = "Fist Weapons",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_gauntlets_04",
        },
        {
            ["id"] = 202,
            ["name"] = "Two-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        {
            ["id"] = 196,
            ["name"] = "One-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_01",
        },
        {
            ["id"] = 264,
            ["name"] = "Bows",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_bow_05",
        },
        {
            ["id"] = 2567,
            ["name"] = "Thrown",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_throwingknife_02",
        },
        {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        {
            ["id"] = 201,
            ["name"] = "One-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        {
            ["id"] = 266,
            ["name"] = "Guns",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_rifle_01",
        },
        {
            ["id"] = 5011,
            ["name"] = "Crossbows",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_crossbow_01",
        },
        {
            ["id"] = 3127,
            ["name"] = "Parry",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_parry",
        },
        {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
        {
            ["id"] = 2764,
            ["name"] = "Throw",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_throw",
        },
    },
    ["mage"] = {
        {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        {
            ["id"] = 201,
            ["name"] = "One-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
        {
            ["id"] = 5009,
            ["name"] = "Wands",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_shootwand",
        },
    },
    ["paladin"] = {
        {
            ["id"] = 200,
            ["name"] = "Polearms",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_spear_06",
        },
        {
            ["id"] = 199,
            ["name"] = "Two-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_04",
        },
        {
            ["id"] = 197,
            ["name"] = "Two-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_04",
        },
        {
            ["id"] = 198,
            ["name"] = "One-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_01",
        },
        {
            ["id"] = 202,
            ["name"] = "Two-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        {
            ["id"] = 196,
            ["name"] = "One-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_01",
        },
        {
            ["id"] = 201,
            ["name"] = "One-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        {
            ["id"] = 107,
            ["name"] = "Block",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_defend",
        },
        {
            ["id"] = 3127,
            ["name"] = "Parry",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_parry",
        },
    },
    ["priest"] = {
        {
            ["id"] = 198,
            ["name"] = "One-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_01",
        },
        {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
        {
            ["id"] = 5009,
            ["name"] = "Wands",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_shootwand",
        },
    },
    ["rogue"] = {
        {
            ["id"] = 674,
            ["name"] = "Dual Wield",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_dualwield",
        },
        {
            ["id"] = 198,
            ["name"] = "One-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_01",
        },
        {
            ["id"] = 15590,
            ["name"] = "Fist Weapons",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_gauntlets_04",
        },
        {
            ["id"] = 264,
            ["name"] = "Bows",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_bow_05",
        },
        {
            ["id"] = 2567,
            ["name"] = "Thrown",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_throwingknife_02",
        },
        {
            ["id"] = 201,
            ["name"] = "One-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        {
            ["id"] = 266,
            ["name"] = "Guns",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_rifle_01",
        },
        {
            ["id"] = 5011,
            ["name"] = "Crossbows",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_crossbow_01",
        },
        {
            ["id"] = 3127,
            ["name"] = "Parry",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_parry",
        },
        {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
        {
            ["id"] = 2764,
            ["name"] = "Throw",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_throw",
        },
    },
    ["shaman"] = {
        {
            ["id"] = 674,
            ["name"] = "Dual Wield",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_dualwield",
        },
        {
            ["id"] = 199,
            ["name"] = "Two-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_04",
        },
        {
            ["id"] = 197,
            ["name"] = "Two-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_04",
        },
        {
            ["id"] = 198,
            ["name"] = "One-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_01",
        },
        {
            ["id"] = 15590,
            ["name"] = "Fist Weapons",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_gauntlets_04",
        },
        {
            ["id"] = 196,
            ["name"] = "One-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_01",
        },
        {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        {
            ["id"] = 107,
            ["name"] = "Block",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_defend",
        },
        {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
    },
    ["warlock"] = {
        {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        {
            ["id"] = 201,
            ["name"] = "One-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
        {
            ["id"] = 5009,
            ["name"] = "Wands",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_shootwand",
        },
    },
    ["warrior"] = {
        {
            ["id"] = 674,
            ["name"] = "Dual Wield",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_dualwield",
        },
        {
            ["id"] = 200,
            ["name"] = "Polearms",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_spear_06",
        },
        {
            ["id"] = 199,
            ["name"] = "Two-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_04",
        },
        {
            ["id"] = 197,
            ["name"] = "Two-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_04",
        },
        {
            ["id"] = 198,
            ["name"] = "One-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_01",
        },
        {
            ["id"] = 15590,
            ["name"] = "Fist Weapons",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_gauntlets_04",
        },
        {
            ["id"] = 202,
            ["name"] = "Two-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        {
            ["id"] = 196,
            ["name"] = "One-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_01",
        },
        {
            ["id"] = 264,
            ["name"] = "Bows",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_bow_05",
        },
        {
            ["id"] = 2567,
            ["name"] = "Thrown",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_throwingknife_02",
        },
        {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        {
            ["id"] = 201,
            ["name"] = "One-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        {
            ["id"] = 107,
            ["name"] = "Block",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_defend",
        },
        {
            ["id"] = 266,
            ["name"] = "Guns",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_rifle_01",
        },
        {
            ["id"] = 5011,
            ["name"] = "Crossbows",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_crossbow_01",
        },
        {
            ["id"] = 3127,
            ["name"] = "Parry",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_parry",
        },
        {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
        {
            ["id"] = 2764,
            ["name"] = "Throw",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_throw",
        }
    }
}

TFG.WEAPON_SKILLS_VANILLA.__CONFIG = { mode = "class" }
