local _, TFG = ...

TFG.DRUID_TBC = {
    [1] = {
        {id=5185, name="Healing Touch", cost=0, rank=1, texture="Interface/ICONS/spell_nature_healingtouch"},
        {id=1126, name="Mark of the Wild", cost=10, rank=1, texture="Interface/ICONS/spell_nature_regeneration"},
        {id=5176, name="Wrath", cost=0, rank=1, texture="Interface/ICONS/spell_nature_abolishmagic"},
    },
    [4] = {
        {id=8921, name="Moonfire", cost=100, rank=1, texture="Interface/ICONS/spell_nature_starfall"},
        {id=774, name="Rejuvenation", cost=100, rank=1, texture="Interface/ICONS/spell_nature_rejuvenation"},
    },
    [6] = {
        {id=467, name="Thorns", cost=100, rank=1, texture="Interface/ICONS/spell_nature_thorns"},
        {id=5177, name="Wrath", cost=100, rank=2, texture="Interface/ICONS/spell_nature_abolishmagic"},
    },
    [8] = {
        {id=339, name="Entangling Roots", cost=200, rank=1, texture="Interface/ICONS/spell_nature_stranglevines"},
        {id=5186, name="Healing Touch", cost=200, rank=2, texture="Interface/ICONS/spell_nature_healingtouch"},
    },
    [10] = {
        {id=5487, name="Bear Form", cost=0, rank=0, texture="Interface/ICONS/ability_racial_bearform"},
        {id=99, name="Demoralizing Roar", cost=300, rank=1, texture="Interface/ICONS/ability_druid_demoralizingroar"},
        {id=6795, name="Growl", cost=0, rank=0, texture="Interface/ICONS/ability_physical_taunt"},
        {id=5232, name="Mark of the Wild", cost=300, rank=2, texture="Interface/ICONS/spell_nature_regeneration"},
        {id=6807, name="Maul", cost=0, rank=1, texture="Interface/ICONS/ability_druid_maul"},
        {id=8924, name="Moonfire", cost=300, rank=2, texture="Interface/ICONS/spell_nature_starfall"},
        {id=1058, name="Rejuvenation", cost=300, rank=2, texture="Interface/ICONS/spell_nature_rejuvenation"},
        {id=18960, name="Teleport: Moonglade", cost=0, rank=0, texture="Interface/ICONS/spell_arcane_teleportmoonglade"},
        {id=16689, name="Nature's Grasp", cost=0, rank=1, texture="Interface/ICONS/spell_nature_natureswrath", talent = 16689},
    },
    [12] = {
        {id=5229, name="Enrage", cost=800, rank=0, texture="Interface/ICONS/ability_druid_enrage"},
        {id=8936, name="Regrowth", cost=800, rank=1, texture="Interface/ICONS/spell_nature_resistnature"},
    },
    [14] = {
        {id=5211, name="Bash", cost=900, rank=1, texture="Interface/ICONS/ability_druid_bash"},
        {id=8946, name="Cure Poison", cost=0, rank=0, texture="Interface/ICONS/spell_nature_nullifypoison"},
        {id=5187, name="Healing Touch", cost=900, rank=3, texture="Interface/ICONS/spell_nature_healingtouch"},
        {id=782, name="Thorns", cost=900, rank=2, texture="Interface/ICONS/spell_nature_thorns"},
        {id=5178, name="Wrath", cost=900, rank=3, texture="Interface/ICONS/spell_nature_abolishmagic"},
    },
    [16] = {
        {id=1066, name="Aquatic Form", cost=0, rank=0, texture="Interface/ICONS/ability_druid_aquaticform"},
        {id=8925, name="Moonfire", cost=1800, rank=3, texture="Interface/ICONS/spell_nature_starfall"},
        {id=1430, name="Rejuvenation", cost=1800, rank=3, texture="Interface/ICONS/spell_nature_rejuvenation"},
        {id=779, name="Swipe", cost=1800, rank=1, texture="Interface/ICONS/inv_misc_monsterclaw_03"},
    },
    [18] = {
        {id=16810, name="Nature's Grasp", cost=95, rank=2, texture="Interface/ICONS/spell_nature_natureswrath", talent = 16689},
        {id=1062, name="Entangling Roots", cost=1900, rank=2, texture="Interface/ICONS/spell_nature_stranglevines"},
        {id=770, name="Faerie Fire", cost=1900, rank=1, texture="Interface/ICONS/spell_nature_faeriefire"},
        {id=2637, name="Hibernate", cost=1900, rank=1, texture="Interface/ICONS/spell_nature_sleep"},
        {id=6808, name="Maul", cost=1900, rank=2, texture="Interface/ICONS/ability_druid_maul"},
        {id=8938, name="Regrowth", cost=1900, rank=2, texture="Interface/ICONS/spell_nature_resistnature"},
    },
    [20] = {
        {id=768, name="Cat Form", cost=2000, rank=0, texture="Interface/ICONS/ability_druid_catform"},
        {id=1082, name="Claw", cost=2000, rank=1, texture="Interface/ICONS/ability_druid_rake"},
        {id=1735, name="Demoralizing Roar", cost=2000, rank=2, texture="Interface/ICONS/ability_druid_demoralizingroar"},
        {id=5188, name="Healing Touch", cost=2000, rank=4, texture="Interface/ICONS/spell_nature_healingtouch"},
        {id=6756, name="Mark of the Wild", cost=2000, rank=3, texture="Interface/ICONS/spell_nature_regeneration"},
        {id=5215, name="Prowl", cost=2000, rank=1, texture="Interface/ICONS/ability_ambush"},
        {id=20484, name="Rebirth", cost=2000, rank=1, texture="Interface/ICONS/spell_nature_reincarnation"},
        {id=1079, name="Rip", cost=2000, rank=1, texture="Interface/ICONS/ability_ghoulfrenzy"},
        {id=2912, name="Starfire", cost=2000, rank=1, texture="Interface/ICONS/spell_arcane_starfire"},
        {id=5570, name="Insect Swarm", cost=0, rank=1, texture="Interface/ICONS/spell_nature_insectswarm", talent = 5570},
        {id=16979, name="Feral Charge", cost=0, rank=0, texture="Interface/ICONS/ability_hunter_pet_bear", talent = true},
        {id=16864, name="Omen of Clarity", cost=0, rank=0, texture="Interface/ICONS/spell_nature_crystalball", talent = true},
    },
    [22] = {
        {id=8926, name="Moonfire", cost=3000, rank=4, texture="Interface/ICONS/spell_nature_starfall"},
        {id=2090, name="Rejuvenation", cost=3000, rank=4, texture="Interface/ICONS/spell_nature_rejuvenation"},
        {id=5221, name="Shred", cost=3000, rank=1, texture="Interface/ICONS/spell_shadow_vampiricaura"},
        {id=2908, name="Soothe Animal", cost=3000, rank=1, texture="Interface/ICONS/ability_hunter_beastsoothe"},
        {id=5179, name="Wrath", cost=3000, rank=4, texture="Interface/ICONS/spell_nature_abolishmagic"},
    },
    [24] = {
        {id=1822, name="Rake", cost=4000, rank=1, texture="Interface/ICONS/ability_druid_disembowel"},
        {id=8939, name="Regrowth", cost=4000, rank=3, texture="Interface/ICONS/spell_nature_resistnature"},
        {id=2782, name="Remove Curse", cost=4000, rank=0, texture="Interface/ICONS/spell_holy_removecurse"},
        {id=780, name="Swipe", cost=4000, rank=2, texture="Interface/ICONS/inv_misc_monsterclaw_03"},
        {id=1075, name="Thorns", cost=4000, rank=3, texture="Interface/ICONS/spell_nature_thorns"},
        {id=5217, name="Tiger's Fury", cost=4000, rank=1, texture="Interface/ICONS/ability_mount_jungletiger"},
    },
    [26] = {
        {id=2893, name="Abolish Poison", cost=4500, rank=0, texture="Interface/ICONS/spell_nature_nullifypoison_02"},
        {id=1850, name="Dash", cost=4500, rank=1, texture="Interface/ICONS/ability_druid_dash"},
        {id=5189, name="Healing Touch", cost=4500, rank=5, texture="Interface/ICONS/spell_nature_healingtouch"},
        {id=6809, name="Maul", cost=4500, rank=3, texture="Interface/ICONS/ability_druid_maul"},
        {id=8949, name="Starfire", cost=4500, rank=2, texture="Interface/ICONS/spell_arcane_starfire"},
    },
    [28] = {
        {id=16811, name="Nature's Grasp", cost=250, rank=3, texture="Interface/ICONS/spell_nature_natureswrath", talent = 16689},
        {id=5209, name="Challenging Roar", cost=5000, rank=0, texture="Interface/ICONS/ability_druid_challangingroar"},
        {id=3029, name="Claw", cost=5000, rank=2, texture="Interface/ICONS/ability_druid_rake"},
        {id=8998, name="Cower", cost=5000, rank=1, texture="Interface/ICONS/ability_druid_cower"},
        {id=5195, name="Entangling Roots", cost=5000, rank=3, texture="Interface/ICONS/spell_nature_stranglevines"},
        {id=8927, name="Moonfire", cost=5000, rank=5, texture="Interface/ICONS/spell_nature_starfall"},
        {id=2091, name="Rejuvenation", cost=5000, rank=5, texture="Interface/ICONS/spell_nature_rejuvenation"},
        {id=9492, name="Rip", cost=5000, rank=2, texture="Interface/ICONS/ability_ghoulfrenzy"},
    },
    [30] = {
        {id=16857, name="Faerie Fire (Feral)", cost=0, rank=1, texture="Interface/ICONS/spell_nature_faeriefire", talent = 16857},
        {id=17390, name="Faerie Fire (Feral)", cost=300, rank=2, texture="Interface/ICONS/spell_nature_faeriefire", talent = 16857},
        {id=24974, name="Insect Swarm", cost=300, rank=2, texture="Interface/ICONS/spell_nature_insectswarm", talent = 5570},
        {id=6798, name="Bash", cost=6000, rank=2, texture="Interface/ICONS/ability_druid_bash"},
        {id=778, name="Faerie Fire", cost=6000, rank=2, texture="Interface/ICONS/spell_nature_faeriefire"},
        {id=5234, name="Mark of the Wild", cost=6000, rank=4, texture="Interface/ICONS/spell_nature_regeneration"},
        {id=20739, name="Rebirth", cost=6000, rank=2, texture="Interface/ICONS/spell_nature_reincarnation"},
        {id=8940, name="Regrowth", cost=6000, rank=4, texture="Interface/ICONS/spell_nature_resistnature"},
        {id=6800, name="Shred", cost=6000, rank=2, texture="Interface/ICONS/spell_shadow_vampiricaura"},
        {id=740, name="Tranquility", cost=6000, rank=1, texture="Interface/ICONS/spell_nature_tranquility"},
        {id=783, name="Travel Form", cost=6000, rank=0, texture="Interface/ICONS/ability_druid_travelform"},
        {id=5180, name="Wrath", cost=6000, rank=5, texture="Interface/ICONS/spell_nature_abolishmagic"},
        {id=17116, name="Nature's Swiftness", cost=0, rank=0, texture="Interface/ICONS/spell_nature_ravenform", talent = true},
    },
    [32] = {
        {id=9490, name="Demoralizing Roar", cost=8000, rank=3, texture="Interface/ICONS/ability_druid_demoralizingroar"},
        {id=22568, name="Ferocious Bite", cost=8000, rank=1, texture="Interface/ICONS/ability_druid_ferociousbite"},
        {id=6778, name="Healing Touch", cost=8000, rank=6, texture="Interface/ICONS/spell_nature_healingtouch"},
        {id=6785, name="Ravage", cost=8000, rank=1, texture="Interface/ICONS/ability_druid_ravage"},
        {id=5225, name="Track Humanoids", cost=8000, rank=0, texture="Interface/ICONS/ability_tracking"},
    },
    [34] = {
        {id=8972, name="Maul", cost=10000, rank=4, texture="Interface/ICONS/ability_druid_maul"},
        {id=8928, name="Moonfire", cost=10000, rank=6, texture="Interface/ICONS/spell_nature_starfall"},
        {id=1823, name="Rake", cost=10000, rank=2, texture="Interface/ICONS/ability_druid_disembowel"},
        {id=3627, name="Rejuvenation", cost=10000, rank=6, texture="Interface/ICONS/spell_nature_rejuvenation"},
        {id=8950, name="Starfire", cost=10000, rank=3, texture="Interface/ICONS/spell_arcane_starfire"},
        {id=769, name="Swipe", cost=10000, rank=3, texture="Interface/ICONS/inv_misc_monsterclaw_03"},
        {id=8914, name="Thorns", cost=10000, rank=4, texture="Interface/ICONS/spell_nature_thorns"},
    },
    [36] = {
        {id=22842, name="Frenzied Regeneration", cost=11000, rank=1, texture="Interface/ICONS/ability_bullrush"},
        {id=9005, name="Pounce", cost=11000, rank=1, texture="Interface/ICONS/ability_druid_supriseattack"},
        {id=8941, name="Regrowth", cost=11000, rank=5, texture="Interface/ICONS/spell_nature_resistnature"},
        {id=9493, name="Rip", cost=11000, rank=3, texture="Interface/ICONS/ability_ghoulfrenzy"},
        {id=6793, name="Tiger's Fury", cost=11000, rank=2, texture="Interface/ICONS/ability_mount_jungletiger"},
    },
    [38] = {
        {id=16812, name="Nature's Grasp", cost=600, rank=4, texture="Interface/ICONS/spell_nature_natureswrath", talent = 16689},
        {id=5201, name="Claw", cost=12000, rank=3, texture="Interface/ICONS/ability_druid_rake"},
        {id=5196, name="Entangling Roots", cost=12000, rank=4, texture="Interface/ICONS/spell_nature_stranglevines"},
        {id=8903, name="Healing Touch", cost=12000, rank=7, texture="Interface/ICONS/spell_nature_healingtouch"},
        {id=18657, name="Hibernate", cost=12000, rank=2, texture="Interface/ICONS/spell_nature_sleep"},
        {id=8992, name="Shred", cost=12000, rank=3, texture="Interface/ICONS/spell_shadow_vampiricaura"},
        {id=8955, name="Soothe Animal", cost=12000, rank=2, texture="Interface/ICONS/ability_hunter_beastsoothe"},
        {id=6780, name="Wrath", cost=12000, rank=6, texture="Interface/ICONS/spell_nature_abolishmagic"},
    },
    [40] = {
        {id=24975, name="Insect Swarm", cost=700, rank=3, texture="Interface/ICONS/spell_nature_insectswarm", talent = 5570},
        {id=9000, name="Cower", cost=14000, rank=2, texture="Interface/ICONS/ability_druid_cower"},
        {id=9634, name="Dire Bear Form", cost=14000, rank=0, texture="Interface/ICONS/ability_racial_bearform"},
        {id=20719, name="Feline Grace", cost=14000, rank=0, texture="Interface/ICONS/inv_feather_01"},
        {id=22827, name="Ferocious Bite", cost=14000, rank=2, texture="Interface/ICONS/ability_druid_ferociousbite"},
        {id=16914, name="Hurricane", cost=14000, rank=1, texture="Interface/ICONS/spell_nature_cyclone"},
        {id=29166, name="Innervate", cost=14000, rank=0, texture="Interface/ICONS/spell_nature_lightning"},
        {id=8907, name="Mark of the Wild", cost=14000, rank=5, texture="Interface/ICONS/spell_nature_regeneration"},
        {id=8929, name="Moonfire", cost=14000, rank=7, texture="Interface/ICONS/spell_nature_starfall"},
        {id=6783, name="Prowl", cost=14000, rank=2, texture="Interface/ICONS/ability_ambush"},
        {id=20742, name="Rebirth", cost=14000, rank=3, texture="Interface/ICONS/spell_nature_reincarnation"},
        {id=8910, name="Rejuvenation", cost=14000, rank=7, texture="Interface/ICONS/spell_nature_rejuvenation"},
        {id=8918, name="Tranquility", cost=14000, rank=2, texture="Interface/ICONS/spell_nature_tranquility"},
        {id=24858, name="Moonkin Form", cost=0, rank=0, texture="Interface/ICONS/spell_nature_forceofnature", talent = true},
        {id=18562, name="Swiftmend", cost=0, rank=0, texture="Interface/ICONS/inv_relics_idolofrejuvenation", talent = true},
    },
    [42] = {
        {id=17391, name="Faerie Fire (Feral)", cost=800, rank=3, texture="Interface/ICONS/spell_nature_faeriefire", talent = 16857},
        {id=9747, name="Demoralizing Roar", cost=16000, rank=4, texture="Interface/ICONS/ability_druid_demoralizingroar"},
        {id=9749, name="Faerie Fire", cost=16000, rank=3, texture="Interface/ICONS/spell_nature_faeriefire"},
        {id=9745, name="Maul", cost=16000, rank=5, texture="Interface/ICONS/ability_druid_maul"},
        {id=6787, name="Ravage", cost=16000, rank=2, texture="Interface/ICONS/ability_druid_ravage"},
        {id=9750, name="Regrowth", cost=16000, rank=6, texture="Interface/ICONS/spell_nature_resistnature"},
        {id=8951, name="Starfire", cost=16000, rank=4, texture="Interface/ICONS/spell_arcane_starfire"},
    },
    [44] = {
        {id=22812, name="Barkskin", cost=18000, rank=0, texture="Interface/ICONS/spell_nature_stoneclawtotem"},
        {id=9758, name="Healing Touch", cost=18000, rank=8, texture="Interface/ICONS/spell_nature_healingtouch"},
        {id=1824, name="Rake", cost=18000, rank=3, texture="Interface/ICONS/ability_druid_disembowel"},
        {id=9752, name="Rip", cost=18000, rank=4, texture="Interface/ICONS/ability_ghoulfrenzy"},
        {id=9754, name="Swipe", cost=18000, rank=4, texture="Interface/ICONS/inv_misc_monsterclaw_03"},
        {id=9756, name="Thorns", cost=18000, rank=5, texture="Interface/ICONS/spell_nature_thorns"},
    },
    [46] = {
        {id=8983, name="Bash", cost=20000, rank=3, texture="Interface/ICONS/ability_druid_bash"},
        {id=9821, name="Dash", cost=20000, rank=2, texture="Interface/ICONS/ability_druid_dash"},
        {id=22895, name="Frenzied Regeneration", cost=20000, rank=2, texture="Interface/ICONS/ability_bullrush"},
        {id=9833, name="Moonfire", cost=20000, rank=8, texture="Interface/ICONS/spell_nature_starfall"},
        {id=9823, name="Pounce", cost=20000, rank=2, texture="Interface/ICONS/ability_druid_supriseattack"},
        {id=9839, name="Rejuvenation", cost=20000, rank=8, texture="Interface/ICONS/spell_nature_rejuvenation"},
        {id=9829, name="Shred", cost=20000, rank=4, texture="Interface/ICONS/spell_shadow_vampiricaura"},
        {id=8905, name="Wrath", cost=20000, rank=7, texture="Interface/ICONS/spell_nature_abolishmagic"},
    },
    [48] = {
        {id=16813, name="Nature's Grasp", cost=1100, rank=5, texture="Interface/ICONS/spell_nature_natureswrath", talent = 16689},
        {id=9849, name="Claw", cost=22000, rank=4, texture="Interface/ICONS/ability_druid_rake"},
        {id=9852, name="Entangling Roots", cost=22000, rank=5, texture="Interface/ICONS/spell_nature_stranglevines"},
        {id=22828, name="Ferocious Bite", cost=22000, rank=3, texture="Interface/ICONS/ability_druid_ferociousbite"},
        {id=9856, name="Regrowth", cost=22000, rank=7, texture="Interface/ICONS/spell_nature_resistnature"},
        {id=9845, name="Tiger's Fury", cost=22000, rank=3, texture="Interface/ICONS/ability_mount_jungletiger"},
    },
    [50] = {
        {id=24976, name="Insect Swarm", cost=1150, rank=4, texture="Interface/ICONS/spell_nature_insectswarm", talent = 5570},
        {id=21849, name="Gift of the Wild", cost=23000, rank=1, texture="Interface/ICONS/spell_nature_giftofthewild"},
        {id=9888, name="Healing Touch", cost=23000, rank=9, texture="Interface/ICONS/spell_nature_healingtouch"},
        {id=17401, name="Hurricane", cost=23000, rank=2, texture="Interface/ICONS/spell_nature_cyclone"},
        {id=33878, name="Mangle (Bear)", cost=0, rank=1, texture="Interface/ICONS/ability_druid_mangle2", talent = 33878},
        {id=33876, name="Mangle (Cat)", cost=0, rank=1, texture="Interface/ICONS/ability_druid_mangle2", talent = 33876},
        {id=9884, name="Mark of the Wild", cost=23000, rank=6, texture="Interface/ICONS/spell_nature_regeneration"},
        {id=9880, name="Maul", cost=23000, rank=6, texture="Interface/ICONS/ability_druid_maul"},
        {id=9866, name="Ravage", cost=23000, rank=3, texture="Interface/ICONS/ability_druid_ravage"},
        {id=20747, name="Rebirth", cost=23000, rank=4, texture="Interface/ICONS/spell_nature_reincarnation"},
        {id=9875, name="Starfire", cost=23000, rank=5, texture="Interface/ICONS/spell_arcane_starfire"},
        {id=9862, name="Tranquility", cost=23000, rank=3, texture="Interface/ICONS/spell_nature_tranquility"},
        {id=33891, name="Tree of Life", cost=0, rank=0, texture="Interface/ICONS/ability_druid_treeoflife", talent = true},
    },
    [52] = {
        {id=9892, name="Cower", cost=26000, rank=3, texture="Interface/ICONS/ability_druid_cower"},
        {id=9898, name="Demoralizing Roar", cost=26000, rank=5, texture="Interface/ICONS/ability_druid_demoralizingroar"},
        {id=9834, name="Moonfire", cost=26000, rank=9, texture="Interface/ICONS/spell_nature_starfall"},
        {id=9840, name="Rejuvenation", cost=26000, rank=9, texture="Interface/ICONS/spell_nature_rejuvenation"},
        {id=9894, name="Rip", cost=26000, rank=5, texture="Interface/ICONS/ability_ghoulfrenzy"},
    },
    [54] = {
        {id=17392, name="Faerie Fire (Feral)", cost=1400, rank=4, texture="Interface/ICONS/spell_nature_faeriefire", talent = 16857},
        {id=9907, name="Faerie Fire", cost=28000, rank=4, texture="Interface/ICONS/spell_nature_faeriefire"},
        {id=9904, name="Rake", cost=28000, rank=4, texture="Interface/ICONS/ability_druid_disembowel"},
        {id=9857, name="Regrowth", cost=28000, rank=8, texture="Interface/ICONS/spell_nature_resistnature"},
        {id=9830, name="Shred", cost=28000, rank=5, texture="Interface/ICONS/spell_shadow_vampiricaura"},
        {id=9901, name="Soothe Animal", cost=28000, rank=3, texture="Interface/ICONS/ability_hunter_beastsoothe"},
        {id=9908, name="Swipe", cost=28000, rank=5, texture="Interface/ICONS/inv_misc_monsterclaw_03"},
        {id=9910, name="Thorns", cost=28000, rank=6, texture="Interface/ICONS/spell_nature_thorns"},
        {id=9912, name="Wrath", cost=28000, rank=8, texture="Interface/ICONS/spell_nature_abolishmagic"},
    },
    [56] = {
        {id=22829, name="Ferocious Bite", cost=30000, rank=4, texture="Interface/ICONS/ability_druid_ferociousbite"},
        {id=22896, name="Frenzied Regeneration", cost=30000, rank=3, texture="Interface/ICONS/ability_bullrush"},
        {id=9889, name="Healing Touch", cost=30000, rank=10, texture="Interface/ICONS/spell_nature_healingtouch"},
        {id=9827, name="Pounce", cost=30000, rank=3, texture="Interface/ICONS/ability_druid_supriseattack"},
    },
    [58] = {
        {id=17329, name="Nature's Grasp", cost=1600, rank=6, texture="Interface/ICONS/spell_nature_natureswrath", talent = 16689},
        {id=9850, name="Claw", cost=32000, rank=5, texture="Interface/ICONS/ability_druid_rake"},
        {id=9853, name="Entangling Roots", cost=32000, rank=6, texture="Interface/ICONS/spell_nature_stranglevines"},
        {id=18658, name="Hibernate", cost=32000, rank=3, texture="Interface/ICONS/spell_nature_sleep"},
        {id=33986, name="Mangle (Bear)", cost=1700, rank=2, texture="Interface/ICONS/ability_druid_mangle2", talent = 33878},
        {id=33982, name="Mangle (Cat)", cost=1700, rank=2, texture="Interface/ICONS/ability_druid_mangle2", talent = 33876},
        {id=9881, name="Maul", cost=32000, rank=7, texture="Interface/ICONS/ability_druid_maul"},
        {id=9835, name="Moonfire", cost=32000, rank=10, texture="Interface/ICONS/spell_nature_starfall"},
        {id=9867, name="Ravage", cost=32000, rank=4, texture="Interface/ICONS/ability_druid_ravage"},
        {id=9841, name="Rejuvenation", cost=32000, rank=10, texture="Interface/ICONS/spell_nature_rejuvenation"},
        {id=9876, name="Starfire", cost=32000, rank=6, texture="Interface/ICONS/spell_arcane_starfire"},
    },
    [60] = {
        {id=24977, name="Insect Swarm", cost=1700, rank=5, texture="Interface/ICONS/spell_nature_insectswarm", talent = 5570},
        {id=31709, name="Cower", cost=34000, rank=4, texture="Interface/ICONS/ability_druid_cower"},
        {id=31018, name="Ferocious Bite", cost=30000, rank=5, texture="Interface/ICONS/ability_druid_ferociousbite"},
        {id=21850, name="Gift of the Wild", cost=34000, rank=2, texture="Interface/ICONS/spell_nature_giftofthewild"},
        {id=25297, name="Healing Touch", cost=34000, rank=11, texture="Interface/ICONS/spell_nature_healingtouch"},
        {id=17402, name="Hurricane", cost=34000, rank=3, texture="Interface/ICONS/spell_nature_cyclone"},
        {id=9885, name="Mark of the Wild", cost=34000, rank=7, texture="Interface/ICONS/spell_nature_regeneration"},
        {id=9913, name="Prowl", cost=34000, rank=3, texture="Interface/ICONS/ability_ambush"},
        {id=20748, name="Rebirth", cost=34000, rank=5, texture="Interface/ICONS/spell_nature_reincarnation"},
        {id=9858, name="Regrowth", cost=34000, rank=9, texture="Interface/ICONS/spell_nature_resistnature"},
        {id=25299, name="Rejuvenation", cost=34000, rank=11, texture="Interface/ICONS/spell_nature_rejuvenation"},
        {id=9896, name="Rip", cost=34000, rank=6, texture="Interface/ICONS/ability_ghoulfrenzy"},
        {id=25298, name="Starfire", cost=34000, rank=7, texture="Interface/ICONS/spell_arcane_starfire"},
        {id=9846, name="Tiger's Fury", cost=34000, rank=4, texture="Interface/ICONS/ability_mount_jungletiger"},
        {id=9863, name="Tranquility", cost=34000, rank=4, texture="Interface/ICONS/spell_nature_tranquility"},
    },
    [61] = {
        {id=27001, name="Shred", cost=39000, rank=6, texture="Interface/ICONS/spell_shadow_vampiricaura"},
        {id=26984, name="Wrath", cost=39000, rank=9, texture="Interface/ICONS/spell_nature_abolishmagic"},
    },
    [62] = {
        {id=26998, name="Demoralizing Roar", cost=43000, rank=6, texture="Interface/ICONS/ability_druid_demoralizingroar"},
        {id=26978, name="Healing Touch", cost=43000, rank=12, texture="Interface/ICONS/spell_nature_healingtouch"},
        {id=22570, name="Maim", cost=43000, rank=1, texture="Interface/ICONS/ability_druid_mangle"},
    },
    [63] = {
        {id=24248, name="Ferocious Bite", cost=48000, rank=6, texture="Interface/ICONS/ability_druid_ferociousbite"},
        {id=26987, name="Moonfire", cost=48000, rank=11, texture="Interface/ICONS/spell_nature_starfall"},
        {id=26981, name="Rejuvenation", cost=48000, rank=12, texture="Interface/ICONS/spell_nature_rejuvenation"},
    },
    [64] = {
        {id=33763, name="Lifebloom", cost=53000, rank=1, texture="Interface/ICONS/inv_misc_herb_felblossom"},
        {id=27003, name="Rake", cost=53000, rank=5, texture="Interface/ICONS/ability_druid_disembowel"},
        {id=26997, name="Swipe", cost=53000, rank=6, texture="Interface/ICONS/inv_misc_monsterclaw_03"},
        {id=26992, name="Thorns", cost=53000, rank=7, texture="Interface/ICONS/spell_nature_thorns"},
    },
    [65] = {
        {id=33357, name="Dash", cost=59000, rank=3, texture="Interface/ICONS/ability_druid_dash"},
        {id=26999, name="Frenzied Regeneration", cost=59000, rank=4, texture="Interface/ICONS/ability_bullrush"},
        {id=26980, name="Regrowth", cost=59000, rank=10, texture="Interface/ICONS/spell_nature_resistnature"},
    },
    [66] = {
        {id=27011, name="Faerie Fire (Feral)", cost=1700, rank=5, texture="Interface/ICONS/spell_nature_faeriefire", talent = 16857},
        {id=26993, name="Faerie Fire", cost=34000, rank=5, texture="Interface/ICONS/spell_nature_faeriefire"},
        {id=33745, name="Lacerate", cost=66000, rank=1, texture="Interface/ICONS/ability_druid_lacerate"},
        {id=27006, name="Pounce", cost=66000, rank=4, texture="Interface/ICONS/ability_druid_supriseattack"},
        {id=27005, name="Ravage", cost=66000, rank=5, texture="Interface/ICONS/ability_druid_ravage"},
    },
    [67] = {
        {id=27000, name="Claw", cost=73000, rank=6, texture="Interface/ICONS/ability_druid_rake"},
        {id=26996, name="Maul", cost=73000, rank=8, texture="Interface/ICONS/ability_druid_maul"},
        {id=27008, name="Rip", cost=73000, rank=7, texture="Interface/ICONS/ability_ghoulfrenzy"},
        {id=26986, name="Starfire", cost=73000, rank=8, texture="Interface/ICONS/spell_arcane_starfire"},
    },
    [68] = {
        {id=27009, name="Nature's Grasp", cost=1700, rank=7, texture="Interface/ICONS/spell_nature_natureswrath", talent = 16689},
        {id=26989, name="Entangling Roots", cost=81000, rank=7, texture="Interface/ICONS/spell_nature_stranglevines"},
        {id=33943, name="Flight Form", cost=81000, rank=0, texture="Interface/ICONS/ability_druid_flightform"},
        {id=33987, name="Mangle (Bear)", cost=1900, rank=3, texture="Interface/ICONS/ability_druid_mangle2", talent = 33878},
        {id=33983, name="Mangle (Cat)", cost=1700, rank=3, texture="Interface/ICONS/ability_druid_mangle2", talent = 33876},
    },
    [69] = {
        {id=27004, name="Cower", cost=90000, rank=5, texture="Interface/ICONS/ability_druid_cower"},
        {id=26979, name="Healing Touch", cost=90000, rank=13, texture="Interface/ICONS/spell_nature_healingtouch"},
        {id=26994, name="Rebirth", cost=90000, rank=6, texture="Interface/ICONS/spell_nature_reincarnation"},
        {id=26982, name="Rejuvenation", cost=90000, rank=13, texture="Interface/ICONS/spell_nature_rejuvenation"},
        {id=26985, name="Wrath", cost=90000, rank=10, texture="Interface/ICONS/spell_nature_abolishmagic"},
    },
    [70] = {
        {id=27013, name="Insect Swarm", cost=2500, rank=6, texture="Interface/ICONS/spell_nature_insectswarm", talent = 5570},
        {id=33786, name="Cyclone", cost=100000, rank=0, texture="Interface/ICONS/spell_nature_earthbind"},
        {id=26991, name="Gift of the Wild", cost=0, rank=3, texture="Interface/ICONS/spell_nature_giftofthewild"},
        {id=27012, name="Hurricane", cost=100000, rank=4, texture="Interface/ICONS/spell_nature_cyclone"},
        {id=26990, name="Mark of the Wild", cost=100000, rank=8, texture="Interface/ICONS/spell_nature_regeneration"},
        {id=26988, name="Moonfire", cost=100000, rank=12, texture="Interface/ICONS/spell_nature_starfall"},
        {id=27002, name="Shred", cost=100000, rank=7, texture="Interface/ICONS/spell_shadow_vampiricaura"},
        {id=26995, name="Soothe Animal", cost=100000, rank=4, texture="Interface/ICONS/ability_hunter_beastsoothe"},
        {id=40120, name="Swift Flight Form", cost=0, rank=0, texture="Interface/ICONS/ability_druid_flightform"},
        {id=26983, name="Tranquility", cost=100000, rank=5, texture="Interface/ICONS/spell_nature_tranquility"},
    },
}