local _, TFG = ...

TFG.HUNTER_PETS_TBC = {
    [1] = {
        {
            spell_id = 2649,
            name = "Growl",
            rank = "1",
            icon = "ability_physical_taunt",
        },
        {
            spell_id = 17253,
            name = "Bite",
            rank = "1",
            icon = "ability_racial_cannibalize",
        },
        {
            spell_id = 35290,
            name = "Gore",
            rank = "1",
            icon = "inv_weapon_shortblade_28",
        },
        {
            spell_id = 34889,
            name = "Fire Breath",
            rank = "1",
            icon = "spell_fire_burnout",
        },
        {
            spell_id = 7371,
            name = "Charge",
            rank = "1",
            icon = "ability_hunter_pet_boar",
        },
        {
            spell_id = 16827,
            name = "Claw",
            rank = "1",
            icon = "ability_druid_rake",
        },
        {
            spell_id = 24545,
            name = "Natural Armor",
            rank = "1",
            icon = "spell_nature_spiritarmor",
        },
        {
            spell_id = 4187,
            name = "Great Stamina",
            rank = "1",
            icon = "spell_nature_unyeildingstamina",
        },
        {
            spell_id = 24844,
            name = "Lightning Breath",
            rank = "1",
            icon = "spell_nature_lightning",
        },
    },
    [5] = {
        {
            spell_id = 1742,
            name = "Cower",
            rank = "1",
            icon = "ability_druid_cower",
        },
    },
    [8] = {
        {
            spell_id = 24423,
            name = "Screech",
            rank = "1",
            icon = "ability_hunter_pet_bat",
        },
        {
            spell_id = 17255,
            name = "Bite",
            rank = "2",
            icon = "ability_racial_cannibalize",
        },
        {
            spell_id = 24640,
            name = "Scorpid Poison",
            rank = "1",
            icon = "ability_poisonsting",
        },
        {
            spell_id = 16828,
            name = "Claw",
            rank = "2",
            icon = "ability_druid_rake",
        },
        {
            spell_id = 35291,
            name = "Gore",
            rank = "2",
            icon = "inv_weapon_shortblade_28",
        },
    },
    [10] = {
        {
            spell_id = 14916,
            name = "Growl",
            rank = "2",
            icon = "ability_physical_taunt",
        },
        {
            spell_id = 24604,
            name = "Furious Howl",
            rank = "1",
            icon = "ability_hunter_pet_wolf",
        },
    },
    [12] = {
        {
            spell_id = 26177,
            name = "Charge",
            rank = "2",
            icon = "ability_hunter_pet_boar",
        },
        {
            spell_id = 4188,
            name = "Great Stamina",
            rank = "2",
            icon = "spell_nature_unyeildingstamina",
        },
        {
            spell_id = 24549,
            name = "Natural Armor",
            rank = "2",
            icon = "spell_nature_spiritarmor",
        },
        {
            spell_id = 25008,
            name = "Lightning Breath",
            rank = "2",
            icon = "spell_nature_lightning",
        },
    },
    [15] = {
        {
            spell_id = 1753,
            name = "Cower",
            rank = "2",
            icon = "ability_druid_cower",
        },
        {
            spell_id = 35387,
            name = "Poison Spit",
            rank = "1",
            icon = "spell_nature_corrosivebreath",
        },
    },
    [16] = {
        {
            spell_id = 35292,
            name = "Gore",
            rank = "3",
            icon = "inv_weapon_shortblade_28",
        },
        {
            spell_id = 17256,
            name = "Bite",
            rank = "3",
            icon = "ability_racial_cannibalize",
        },
        {
            spell_id = 16829,
            name = "Claw",
            rank = "3",
            icon = "ability_druid_rake",
        },
    },
    [18] = {
        {
            spell_id = 4189,
            name = "Great Stamina",
            rank = "3",
            icon = "spell_nature_unyeildingstamina",
        },
        {
            spell_id = 24550,
            name = "Natural Armor",
            rank = "3",
            icon = "spell_nature_spiritarmor",
        },
    },
    [20] = {
        {
            spell_id = 24493,
            name = "Arcane Resistance",
            rank = "1",
            icon = "spell_nature_starfall",
        },
        {
            spell_id = 26064,
            name = "Shell Shield",
            rank = "1",
            icon = "ability_hunter_pet_turtle",
        },
        {
            spell_id = 14917,
            name = "Growl",
            rank = "3",
            icon = "ability_physical_taunt",
        },
        {
            spell_id = 24488,
            name = "Shadow Resistance",
            rank = "1",
            icon = "spell_shadow_antishadow",
        },
        {
            spell_id = 23992,
            name = "Fire Resistance",
            rank = "1",
            icon = "spell_fire_firearmor",
        },
        {
            spell_id = 24446,
            name = "Frost Resistance",
            rank = "1",
            icon = "spell_frost_frostward",
        },
        {
            spell_id = 24492,
            name = "Nature Resistance",
            rank = "1",
            icon = "spell_nature_resistnature",
        },
    },
    [24] = {
        {
            spell_id = 16830,
            name = "Claw",
            rank = "4",
            icon = "ability_druid_rake",
        },
        {
            spell_id = 35293,
            name = "Gore",
            rank = "4",
            icon = "inv_weapon_shortblade_28",
        },
        {
            spell_id = 17257,
            name = "Bite",
            rank = "4",
            icon = "ability_racial_cannibalize",
        },
        {
            spell_id = 25009,
            name = "Lightning Breath",
            rank = "3",
            icon = "spell_nature_lightning",
        },
        {
            spell_id = 4190,
            name = "Great Stamina",
            rank = "4",
            icon = "spell_nature_unyeildingstamina",
        },
        {
            spell_id = 26178,
            name = "Charge",
            rank = "3",
            icon = "ability_hunter_pet_boar",
        },
        {
            spell_id = 24605,
            name = "Furious Howl",
            rank = "2",
            icon = "ability_hunter_pet_wolf",
        },
        {
            spell_id = 24583,
            name = "Scorpid Poison",
            rank = "2",
            icon = "ability_poisonsting",
        },
        {
            spell_id = 24577,
            name = "Screech",
            rank = "2",
            icon = "ability_hunter_pet_bat",
        },
        {
            spell_id = 24551,
            name = "Natural Armor",
            rank = "4",
            icon = "spell_nature_spiritarmor",
        },
    },
    [25] = {
        {
            spell_id = 1754,
            name = "Cower",
            rank = "3",
            icon = "ability_druid_cower",
        },
    },
    [30] = {
        {
            spell_id = 25076,
            name = "Cobra Reflexes",
            rank = "1",
            icon = "spell_nature_guardianward",
        },
        {
            spell_id = 23099,
            name = "Dash",
            rank = "1",
            icon = "ability_druid_dash",
        },
        {
            spell_id = 23145,
            name = "Dive",
            rank = "1",
            icon = "spell_shadow_burningspirit",
        },
        {
            spell_id = 35694,
            name = "Avoidance",
            rank = "1",
            icon = "spell_magic_lesserinvisibilty",
        },
        {
            spell_id = 24450,
            name = "Prowl",
            rank = "1",
            icon = "ability_druid_supriseattack",
        },
        {
            spell_id = 4191,
            name = "Great Stamina",
            rank = "5",
            icon = "spell_nature_unyeildingstamina",
        },
        {
            spell_id = 14918,
            name = "Growl",
            rank = "4",
            icon = "ability_physical_taunt",
        },
        {
            spell_id = 26090,
            name = "Thunderstomp",
            rank = "1",
            icon = "ability_hunter_pet_gorilla",
        },
        {
            spell_id = 24505,
            name = "Shadow Resistance",
            rank = "2",
            icon = "spell_shadow_antishadow",
        },
        {
            spell_id = 24447,
            name = "Frost Resistance",
            rank = "2",
            icon = "spell_frost_frostward",
        },
        {
            spell_id = 24552,
            name = "Natural Armor",
            rank = "5",
            icon = "spell_nature_spiritarmor",
        },
        {
            spell_id = 24502,
            name = "Nature Resistance",
            rank = "2",
            icon = "spell_nature_resistnature",
        },
        {
            spell_id = 24439,
            name = "Fire Resistance",
            rank = "2",
            icon = "spell_fire_firearmor",
        },
        {
            spell_id = 24497,
            name = "Arcane Resistance",
            rank = "2",
            icon = "spell_nature_starfall",
        },
    },
    [32] = {
        {
            spell_id = 17258,
            name = "Bite",
            rank = "5",
            icon = "ability_racial_cannibalize",
        },
        {
            spell_id = 16831,
            name = "Claw",
            rank = "5",
            icon = "ability_druid_rake",
        },
        {
            spell_id = 35294,
            name = "Gore",
            rank = "5",
            icon = "inv_weapon_shortblade_28",
        },
    },
    [35] = {
        {
            spell_id = 1755,
            name = "Cower",
            rank = "4",
            icon = "ability_druid_cower",
        },
    },
    [36] = {
        {
            spell_id = 4192,
            name = "Great Stamina",
            rank = "6",
            icon = "spell_nature_unyeildingstamina",
        },
        {
            spell_id = 24553,
            name = "Natural Armor",
            rank = "6",
            icon = "spell_nature_spiritarmor",
        },
        {
            spell_id = 25010,
            name = "Lightning Breath",
            rank = "4",
            icon = "spell_nature_lightning",
        },
        {
            spell_id = 26179,
            name = "Charge",
            rank = "4",
            icon = "ability_hunter_pet_boar",
        },
    },
    [40] = {
        {
            spell_id = 23109,
            name = "Dash",
            rank = "2",
            icon = "ability_druid_dash",
        },
        {
            spell_id = 35295,
            name = "Gore",
            rank = "6",
            icon = "inv_weapon_shortblade_28",
        },
        {
            spell_id = 14919,
            name = "Growl",
            rank = "5",
            icon = "ability_physical_taunt",
        },
        {
            spell_id = 23147,
            name = "Dive",
            rank = "2",
            icon = "spell_shadow_burningspirit",
        },
        {
            spell_id = 17259,
            name = "Bite",
            rank = "6",
            icon = "ability_racial_cannibalize",
        },
        {
            spell_id = 16832,
            name = "Claw",
            rank = "6",
            icon = "ability_druid_rake",
        },
        {
            spell_id = 24444,
            name = "Fire Resistance",
            rank = "3",
            icon = "spell_fire_firearmor",
        },
        {
            spell_id = 24506,
            name = "Shadow Resistance",
            rank = "3",
            icon = "spell_shadow_antishadow",
        },
        {
            spell_id = 24603,
            name = "Furious Howl",
            rank = "3",
            icon = "ability_hunter_pet_wolf",
        },
        {
            spell_id = 26187,
            name = "Thunderstomp",
            rank = "2",
            icon = "ability_hunter_pet_gorilla",
        },
        {
            spell_id = 24452,
            name = "Prowl",
            rank = "2",
            icon = "ability_druid_supriseattack",
        },
        {
            spell_id = 24503,
            name = "Nature Resistance",
            rank = "3",
            icon = "spell_nature_resistnature",
        },
        {
            spell_id = 24500,
            name = "Arcane Resistance",
            rank = "3",
            icon = "spell_nature_starfall",
        },
        {
            spell_id = 24448,
            name = "Frost Resistance",
            rank = "3",
            icon = "spell_frost_frostward",
        },
        {
            spell_id = 24586,
            name = "Scorpid Poison",
            rank = "3",
            icon = "ability_poisonsting",
        },
    },
    [42] = {
        {
            spell_id = 4193,
            name = "Great Stamina",
            rank = "7",
            icon = "spell_nature_unyeildingstamina",
        },
        {
            spell_id = 24554,
            name = "Natural Armor",
            rank = "7",
            icon = "spell_nature_spiritarmor",
        },
    },
    [45] = {
        {
            spell_id = 1756,
            name = "Cower",
            rank = "5",
            icon = "ability_druid_cower",
        },
        {
            spell_id = 35389,
            name = "Poison Spit",
            rank = "2",
            icon = "spell_nature_corrosivebreath",
        },
    },
    [48] = {
        {
            spell_id = 17260,
            name = "Bite",
            rank = "7",
            icon = "ability_racial_cannibalize",
        },
        {
            spell_id = 3010,
            name = "Claw",
            rank = "7",
            icon = "ability_druid_rake",
        },
        {
            spell_id = 35296,
            name = "Gore",
            rank = "7",
            icon = "inv_weapon_shortblade_28",
        },
        {
            spell_id = 4194,
            name = "Great Stamina",
            rank = "8",
            icon = "spell_nature_unyeildingstamina",
        },
        {
            spell_id = 24578,
            name = "Screech",
            rank = "3",
            icon = "ability_hunter_pet_bat",
        },
        {
            spell_id = 24555,
            name = "Natural Armor",
            rank = "8",
            icon = "spell_nature_spiritarmor",
        },
        {
            spell_id = 25011,
            name = "Lightning Breath",
            rank = "5",
            icon = "spell_nature_lightning",
        },
        {
            spell_id = 26201,
            name = "Charge",
            rank = "5",
            icon = "ability_hunter_pet_boar",
        },
    },
    [50] = {
        {
            spell_id = 23110,
            name = "Dash",
            rank = "3",
            icon = "ability_druid_dash",
        },
        {
            spell_id = 23148,
            name = "Dive",
            rank = "3",
            icon = "spell_shadow_burningspirit",
        },
        {
            spell_id = 24453,
            name = "Prowl",
            rank = "3",
            icon = "ability_druid_supriseattack",
        },
        {
            spell_id = 26188,
            name = "Thunderstomp",
            rank = "3",
            icon = "ability_hunter_pet_gorilla",
        },
        {
            spell_id = 14920,
            name = "Growl",
            rank = "6",
            icon = "ability_physical_taunt",
        },
        {
            spell_id = 24501,
            name = "Arcane Resistance",
            rank = "4",
            icon = "spell_nature_starfall",
        },
        {
            spell_id = 24504,
            name = "Nature Resistance",
            rank = "4",
            icon = "spell_nature_resistnature",
        },
        {
            spell_id = 24507,
            name = "Shadow Resistance",
            rank = "4",
            icon = "spell_shadow_antishadow",
        },
        {
            spell_id = 24445,
            name = "Fire Resistance",
            rank = "4",
            icon = "spell_fire_firearmor",
        },
        {
            spell_id = 24449,
            name = "Frost Resistance",
            rank = "4",
            icon = "spell_frost_frostward",
        },
    },
    [54] = {
        {
            spell_id = 5041,
            name = "Great Stamina",
            rank = "9",
            icon = "spell_nature_unyeildingstamina",
        },
        {
            spell_id = 24629,
            name = "Natural Armor",
            rank = "9",
            icon = "spell_nature_spiritarmor",
        },
    },
    [55] = {
        {
            spell_id = 16697,
            name = "Cower",
            rank = "6",
            icon = "ability_druid_cower",
        },
    },
    [56] = {
        {
            spell_id = 24597,
            name = "Furious Howl",
            rank = "4",
            icon = "ability_hunter_pet_wolf",
        },
        {
            spell_id = 24579,
            name = "Screech",
            rank = "4",
            icon = "ability_hunter_pet_bat",
        },
        {
            spell_id = 17261,
            name = "Bite",
            rank = "8",
            icon = "ability_racial_cannibalize",
        },
        {
            spell_id = 35297,
            name = "Gore",
            rank = "8",
            icon = "inv_weapon_shortblade_28",
        },
        {
            spell_id = 3009,
            name = "Claw",
            rank = "8",
            icon = "ability_druid_rake",
        },
        {
            spell_id = 24587,
            name = "Scorpid Poison",
            rank = "4",
            icon = "ability_poisonsting",
        },
    },
    [60] = {
        {
            spell_id = 25012,
            name = "Lightning Breath",
            rank = "6",
            icon = "spell_nature_lightning",
        },
        {
            spell_id = 27685,
            name = "Charge",
            rank = "6",
            icon = "ability_hunter_pet_boar",
        },
        {
            spell_id = 14921,
            name = "Growl",
            rank = "7",
            icon = "ability_physical_taunt",
        },
        {
            spell_id = 35323,
            name = "Fire Breath",
            rank = "2",
            icon = "spell_fire_burnout",
        },
        {
            spell_id = 27063,
            name = "Thunderstomp",
            rank = "4",
            icon = "ability_hunter_pet_gorilla",
        },
        {
            spell_id = 35698,
            name = "Avoidance",
            rank = "1",
            icon = "spell_magic_lesserinvisibilty",
        },
        {
            spell_id = 5042,
            name = "Great Stamina",
            rank = "10",
            icon = "spell_nature_unyeildingstamina",
        },
        {
            spell_id = 27054,
            name = "Frost Resistance",
            rank = "5",
            icon = "spell_frost_frostward",
        },
        {
            spell_id = 27052,
            name = "Arcane Resistance",
            rank = "5",
            icon = "spell_nature_starfall",
        },
        {
            spell_id = 35392,
            name = "Poison Spit",
            rank = "3",
            icon = "spell_nature_corrosivebreath",
        },
        {
            spell_id = 27055,
            name = "Nature Resistance",
            rank = "5",
            icon = "spell_nature_resistnature",
        },
        {
            spell_id = 24630,
            name = "Natural Armor",
            rank = "10",
            icon = "spell_nature_spiritarmor",
        },
        {
            spell_id = 27053,
            name = "Fire Resistance",
            rank = "5",
            icon = "spell_fire_firearmor",
        },
        {
            spell_id = 35346,
            name = "Warp",
            rank = "1",
            icon = "spell_arcane_arcane04",
        },
        {
            spell_id = 27056,
            name = "Shadow Resistance",
            rank = "5",
            icon = "spell_shadow_antishadow",
        },
    },
    [63] = {
        {
            spell_id = 35298,
            name = "Gore",
            rank = "9",
            icon = "inv_weapon_shortblade_28",
        },
    },
    [64] = {
        {
            spell_id = 27050,
            name = "Bite",
            rank = "9",
            icon = "ability_racial_cannibalize",
        },
        {
            spell_id = 27049,
            name = "Claw",
            rank = "9",
            icon = "ability_druid_rake",
        },
        {
            spell_id = 27051,
            name = "Screech",
            rank = "5",
            icon = "ability_hunter_pet_bat",
        },
        {
            spell_id = 27060,
            name = "Scorpid Poison",
            rank = "5",
            icon = "ability_poisonsting",
        },
    },
    [65] = {
        {
            spell_id = 27048,
            name = "Cower",
            rank = "7",
            icon = "ability_druid_cower",
        },
    },
    [70] = {
        {
            spell_id = 27047,
            name = "Growl",
            rank = "8",
            icon = "ability_physical_taunt",
        },
        {
            spell_id = 27061,
            name = "Natural Armor",
            rank = "11",
            icon = "spell_nature_spiritarmor",
        },
        {
            spell_id = 27062,
            name = "Great Stamina",
            rank = "11",
            icon = "spell_nature_unyeildingstamina",
        },
    },
}
