local _, TFG = ...

TFG.MAGE_TBC = {
    [1] = {
        {id=5019, name="Shoot", cost=0, rank=0, texture="Interface/ICONS/ability_shootwand"},
        {id=1459, name="Arcane Intellect", cost=10, rank=1, texture="Interface/ICONS/spell_holy_magicalsentry"},
        {id=133, name="Fireball", cost=0, rank=1, texture="Interface/ICONS/spell_fire_flamebolt"},
        {id=168, name="Frost Armor", cost=0, rank=1, texture="Interface/ICONS/spell_frost_frostarmor02"},
    },
    [4] = {
        {id=5504, name="Conjure Water", cost=100, rank=1, texture="Interface/ICONS/inv_drink_06"},
        {id=116, name="Frostbolt", cost=100, rank=1, texture="Interface/ICONS/spell_frost_frostbolt02"},
    },
    [6] = {
        {id=587, name="Conjure Food", cost=100, rank=1, texture="Interface/ICONS/inv_misc_food_10"},
        {id=2136, name="Fire Blast", cost=100, rank=1, texture="Interface/ICONS/spell_fire_fireball"},
        {id=143, name="Fireball", cost=100, rank=2, texture="Interface/ICONS/spell_fire_flamebolt"},
    },
    [8] = {
        {id=5143, name="Arcane Missiles", cost=200, rank=1, texture="Interface/ICONS/spell_nature_starfall"},
        {id=205, name="Frostbolt", cost=200, rank=2, texture="Interface/ICONS/spell_frost_frostbolt02"},
        {id=118, name="Polymorph", cost=200, rank=1, texture="Interface/ICONS/spell_nature_polymorph"},
    },
    [10] = {
        {id=5505, name="Conjure Water", cost=400, rank=2, texture="Interface/ICONS/inv_drink_07"},
        {id=7300, name="Frost Armor", cost=400, rank=2, texture="Interface/ICONS/spell_frost_frostarmor02"},
        {id=122, name="Frost Nova", cost=400, rank=1, texture="Interface/ICONS/spell_frost_frostnova"},
    },
    [12] = {
        {id=597, name="Conjure Food", cost=600, rank=2, texture="Interface/ICONS/inv_misc_food_09"},
        {id=604, name="Dampen Magic", cost=600, rank=1, texture="Interface/ICONS/spell_nature_abolishmagic"},
        {id=145, name="Fireball", cost=600, rank=3, texture="Interface/ICONS/spell_fire_flamebolt"},
        {id=130, name="Slow Fall", cost=600, rank=0, texture="Interface/ICONS/spell_magic_featherfall"},
    },
    [14] = {
        {id=1449, name="Arcane Explosion", cost=900, rank=1, texture="Interface/ICONS/spell_nature_wispsplode"},
        {id=1460, name="Arcane Intellect", cost=900, rank=2, texture="Interface/ICONS/spell_holy_magicalsentry"},
        {id=2137, name="Fire Blast", cost=900, rank=2, texture="Interface/ICONS/spell_fire_fireball"},
        {id=837, name="Frostbolt", cost=900, rank=3, texture="Interface/ICONS/spell_frost_frostbolt02"},
    },
    [16] = {
        {id=5144, name="Arcane Missiles", cost=1500, rank=2, texture="Interface/ICONS/spell_nature_starfall"},
        {id=2120, name="Flamestrike", cost=1500, rank=1, texture="Interface/ICONS/spell_fire_selfdestruct"},
    },
    [18] = {
        {id=1008, name="Amplify Magic", cost=1800, rank=1, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=3140, name="Fireball", cost=1800, rank=4, texture="Interface/ICONS/spell_fire_flamebolt"},
        {id=475, name="Remove Lesser Curse", cost=1800, rank=0, texture="Interface/ICONS/spell_nature_removecurse"},
    },
    [20] = {
        {id=1953, name="Blink", cost=2000, rank=0, texture="Interface/ICONS/spell_arcane_blink"},
        {id=10, name="Blizzard", cost=2000, rank=1, texture="Interface/ICONS/spell_frost_icestorm"},
        {id=5506, name="Conjure Water", cost=2000, rank=3, texture="Interface/ICONS/inv_drink_milk_02"},
        {id=12051, name="Evocation", cost=2000, rank=0, texture="Interface/ICONS/spell_nature_purge"},
        {id=543, name="Fire Ward", cost=2000, rank=1, texture="Interface/ICONS/spell_fire_firearmor"},
        {id=7301, name="Frost Armor", cost=2000, rank=3, texture="Interface/ICONS/spell_frost_frostarmor02"},
        {id=7322, name="Frostbolt", cost=2000, rank=4, texture="Interface/ICONS/spell_frost_frostbolt02"},
        {id=1463, name="Mana Shield", cost=2000, rank=1, texture="Interface/ICONS/spell_shadow_detectlesserinvisibility"},
        {id=12824, name="Polymorph", cost=2000, rank=2, texture="Interface/ICONS/spell_nature_polymorph"},
        {id=3561, name="Teleport: Stormwind", cost=2000, rank=0, faction="Alliance", texture="Interface/ICONS/spell_arcane_teleportstormwind"},
        {id=3562, name="Teleport: Ironforge", cost=2000, rank=0, faction="Alliance", texture="Interface/ICONS/spell_arcane_teleportironforge"},
        {id=32271, name="Teleport: Exodar", cost=1900, rank=0, faction="Alliance", texture="Interface/ICONS/spell_arcane_teleportexodar"},
        {id=3567, name="Teleport: Orgrimmar", cost=2000, rank=0, faction="Horde", texture="Interface/ICONS/spell_arcane_teleportorgrimmar"},
        {id=3563, name="Teleport: Undercity", cost=2000, rank=0, faction="Horde", texture="Interface/ICONS/spell_arcane_teleportundercity"},
        {id=32272, name="Teleport: Silvermoon", cost=2000, rank=0, faction="Horde", texture="Interface/ICONS/spell_arcane_teleportsilvermoon"},
        {id=11366, name="Pyroblast", cost=0, rank=1, texture="Interface/ICONS/spell_fire_fireball02", talent = 11366},
        {id=12472, name="Icy Veins", cost=0, rank=0, texture="Interface/ICONS/spell_frost_coldhearted", talent = true},
    },
    [22] = {
        {id=8437, name="Arcane Explosion", cost=3000, rank=2, texture="Interface/ICONS/spell_nature_wispsplode"},
        {id=990, name="Conjure Food", cost=3000, rank=3, texture="Interface/ICONS/inv_misc_food_12"},
        {id=2138, name="Fire Blast", cost=3000, rank=3, texture="Interface/ICONS/spell_fire_fireball"},
        {id=6143, name="Frost Ward", cost=3000, rank=1, texture="Interface/ICONS/spell_frost_frostward"},
        {id=2948, name="Scorch", cost=3000, rank=1, texture="Interface/ICONS/spell_fire_soulburn"},
    },
    [24] = {
        {id=12505, name="Pyroblast", cost=200, rank=2, texture="Interface/ICONS/spell_fire_fireball02", talent = 11366},
        {id=5145, name="Arcane Missiles", cost=4000, rank=3, texture="Interface/ICONS/spell_nature_starfall"},
        {id=2139, name="Counterspell", cost=4000, rank=0, texture="Interface/ICONS/spell_frost_iceshock"},
        {id=8450, name="Dampen Magic", cost=4000, rank=2, texture="Interface/ICONS/spell_nature_abolishmagic"},
        {id=8400, name="Fireball", cost=4000, rank=5, texture="Interface/ICONS/spell_fire_flamebolt"},
        {id=2121, name="Flamestrike", cost=4000, rank=2, texture="Interface/ICONS/spell_fire_selfdestruct"},
    },
    [26] = {
        {id=120, name="Cone of Cold", cost=5000, rank=1, texture="Interface/ICONS/spell_frost_glacier"},
        {id=865, name="Frost Nova", cost=5000, rank=2, texture="Interface/ICONS/spell_frost_frostnova"},
        {id=8406, name="Frostbolt", cost=5000, rank=5, texture="Interface/ICONS/spell_frost_frostbolt02"},
    },
    [28] = {
        {id=1461, name="Arcane Intellect", cost=7000, rank=3, texture="Interface/ICONS/spell_holy_magicalsentry"},
        {id=6141, name="Blizzard", cost=7000, rank=2, texture="Interface/ICONS/spell_frost_icestorm"},
        {id=759, name="Conjure Mana Agate", cost=7000, rank=0, texture="Interface/ICONS/inv_misc_gem_emerald_01"},
        {id=8494, name="Mana Shield", cost=7000, rank=2, texture="Interface/ICONS/spell_shadow_detectlesserinvisibility"},
        {id=8444, name="Scorch", cost=7000, rank=2, texture="Interface/ICONS/spell_fire_soulburn"},
    },
    [30] = {
        {id=12522, name="Pyroblast", cost=400, rank=3, texture="Interface/ICONS/spell_fire_fireball02", talent = 11366},
        {id=8455, name="Amplify Magic", cost=8000, rank=2, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=8438, name="Arcane Explosion", cost=8000, rank=3, texture="Interface/ICONS/spell_nature_wispsplode"},
        {id=6127, name="Conjure Water", cost=8000, rank=4, texture="Interface/ICONS/inv_drink_10"},
        {id=8412, name="Fire Blast", cost=8000, rank=4, texture="Interface/ICONS/spell_fire_fireball"},
        {id=8457, name="Fire Ward", cost=8000, rank=2, texture="Interface/ICONS/spell_fire_firearmor"},
        {id=8401, name="Fireball", cost=8000, rank=6, texture="Interface/ICONS/spell_fire_flamebolt"},
        {id=7302, name="Ice Armor", cost=8000, rank=1, texture="Interface/ICONS/spell_frost_frostarmor02"},
        {id=45438, name="Ice Block", cost=8000, rank=0, texture="Interface/ICONS/spell_frost_frost"},
        {id=3565, name="Teleport: Darnassus", cost=8000, rank=0, faction="Alliance", texture="Interface/ICONS/spell_arcane_teleportdarnassus"},
        {id=3566, name="Teleport: Thunder Bluff", cost=8000, rank=0, faction="Horde", texture="Interface/ICONS/spell_arcane_teleportthunderbluff"},
        {id=12043, name="Presence of Mind", cost=0, rank=0, texture="Interface/ICONS/spell_nature_enchantarmor", talent = true},
        {id=11113, name="Blast Wave", cost=0, rank=1, texture="Interface/ICONS/spell_holy_excorcism_02", talent = 11113},
        {id=11958, name="Cold Snap", cost=0, rank=0, texture="Interface/ICONS/spell_frost_wizardmark", talent = true},
    },
    [32] = {
        {id=8416, name="Arcane Missiles", cost=10000, rank=4, texture="Interface/ICONS/spell_nature_starfall"},
        {id=6129, name="Conjure Food", cost=10000, rank=4, texture="Interface/ICONS/inv_misc_food_08"},
        {id=8422, name="Flamestrike", cost=10000, rank=3, texture="Interface/ICONS/spell_fire_selfdestruct"},
        {id=8461, name="Frost Ward", cost=10000, rank=2, texture="Interface/ICONS/spell_frost_frostward"},
        {id=8407, name="Frostbolt", cost=10000, rank=6, texture="Interface/ICONS/spell_frost_frostbolt02"},
    },
    [34] = {
        {id=8492, name="Cone of Cold", cost=12000, rank=2, texture="Interface/ICONS/spell_frost_glacier"},
        {id=6117, name="Mage Armor", cost=13000, rank=1, texture="Interface/ICONS/spell_magearmor"},
        {id=8445, name="Scorch", cost=12000, rank=3, texture="Interface/ICONS/spell_fire_soulburn"},
    },
    [35] = {
        {id=49359, name="Teleport: Theramore", cost=2000, rank=0, faction="Alliance", texture="Interface/ICONS/spell_arcane_teleporttheramore"},
        {id=49360, name="Portal: Theramore", cost=15000, rank=0, faction="Alliance", texture="Interface/ICONS/spell_arcane_portaltheramore"},
        {id=49358, name="Teleport: Stonard", cost=2000, rank=0, faction="Horde", texture="Interface/ICONS/spell_arcane_teleportstonard"},
        {id=49361, name="Portal: Stonard", cost=15000, rank=0, faction="Horde", texture="Interface/ICONS/spell_arcane_portalstonard"},
    },
    [36] = {
        {id=13018, name="Blast Wave", cost=650, rank=2, texture="Interface/ICONS/spell_holy_excorcism_02", talent = 11113},
        {id=12523, name="Pyroblast", cost=650, rank=4, texture="Interface/ICONS/spell_fire_fireball02", talent = 11366},
        {id=8427, name="Blizzard", cost=13000, rank=3, texture="Interface/ICONS/spell_frost_icestorm"},
        {id=8451, name="Dampen Magic", cost=13000, rank=3, texture="Interface/ICONS/spell_nature_abolishmagic"},
        {id=8402, name="Fireball", cost=13000, rank=7, texture="Interface/ICONS/spell_fire_flamebolt"},
        {id=8495, name="Mana Shield", cost=13000, rank=3, texture="Interface/ICONS/spell_shadow_detectlesserinvisibility"},
    },
    [38] = {
        {id=8439, name="Arcane Explosion", cost=14000, rank=4, texture="Interface/ICONS/spell_nature_wispsplode"},
        {id=3552, name="Conjure Mana Jade", cost=14000, rank=0, texture="Interface/ICONS/inv_misc_gem_emerald_02"},
        {id=8413, name="Fire Blast", cost=14000, rank=5, texture="Interface/ICONS/spell_fire_fireball"},
        {id=8408, name="Frostbolt", cost=14000, rank=7, texture="Interface/ICONS/spell_frost_frostbolt02"},
    },
    [40] = {
        {id=8417, name="Arcane Missiles", cost=15000, rank=5, texture="Interface/ICONS/spell_nature_starfall"},
        {id=10138, name="Conjure Water", cost=15000, rank=5, texture="Interface/ICONS/inv_drink_09"},
        {id=8458, name="Fire Ward", cost=15000, rank=3, texture="Interface/ICONS/spell_fire_firearmor"},
        {id=8423, name="Flamestrike", cost=15000, rank=4, texture="Interface/ICONS/spell_fire_selfdestruct"},
        {id=6131, name="Frost Nova", cost=15000, rank=3, texture="Interface/ICONS/spell_frost_frostnova"},
        {id=7320, name="Ice Armor", cost=15000, rank=2, texture="Interface/ICONS/spell_frost_frostarmor02"},
        {id=12825, name="Polymorph", cost=15000, rank=3, texture="Interface/ICONS/spell_nature_polymorph"},
        {id=32266, name="Portal: Exodar", cost=14250, rank=0, faction="Alliance", texture="Interface/ICONS/spell_arcane_portalexodar"},
        {id=11416, name="Portal: Ironforge", cost=15000, rank=0, faction="Alliance", texture="Interface/ICONS/spell_arcane_portalironforge"},
        {id=11417, name="Portal: Orgrimmar", cost=15000, rank=0, faction="Horde", texture="Interface/ICONS/spell_arcane_portalorgrimmar"},
        {id=32267, name="Portal: Silvermoon", cost=15000, rank=0, faction="Horde", texture="Interface/ICONS/spell_arcane_portalsilvermoon"},
        {id=10059, name="Portal: Stormwind", cost=15000, rank=0, faction="Alliance", texture="Interface/ICONS/spell_arcane_portalstormwind"},
        {id=11418, name="Portal: Undercity", cost=15000, rank=0, faction="Horde", texture="Interface/ICONS/spell_arcane_portalundercity"},
        {id=8446, name="Scorch", cost=15000, rank=4, texture="Interface/ICONS/spell_fire_soulburn"},
        {id=12042, name="Arcane Power", cost=0, rank=0, texture="Interface/ICONS/spell_nature_lightning", talent = true},
        {id=11129, name="Combustion", cost=0, rank=0, texture="Interface/ICONS/spell_fire_sealoffire", talent = true},
        {id=11426, name="Ice Barrier", cost=0, rank=1, texture="Interface/ICONS/spell_ice_lament", talent = 11426},
    },
    [42] = {
        {id=12524, name="Pyroblast", cost=900, rank=5, texture="Interface/ICONS/spell_fire_fireball02", talent = 11366},
        {id=10169, name="Amplify Magic", cost=18000, rank=3, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=10156, name="Arcane Intellect", cost=18000, rank=4, texture="Interface/ICONS/spell_holy_magicalsentry"},
        {id=10159, name="Cone of Cold", cost=18000, rank=3, texture="Interface/ICONS/spell_frost_glacier"},
        {id=10144, name="Conjure Food", cost=18000, rank=5, texture="Interface/ICONS/inv_misc_food_11"},
        {id=10148, name="Fireball", cost=18000, rank=8, texture="Interface/ICONS/spell_fire_flamebolt"},
        {id=8462, name="Frost Ward", cost=18000, rank=3, texture="Interface/ICONS/spell_frost_frostward"},
    },
    [44] = {
        {id=13019, name="Blast Wave", cost=1150, rank=3, texture="Interface/ICONS/spell_holy_excorcism_02", talent = 11113},
        {id=10185, name="Blizzard", cost=23000, rank=4, texture="Interface/ICONS/spell_frost_icestorm"},
        {id=10179, name="Frostbolt", cost=23000, rank=8, texture="Interface/ICONS/spell_frost_frostbolt02"},
        {id=10191, name="Mana Shield", cost=23000, rank=4, texture="Interface/ICONS/spell_shadow_detectlesserinvisibility"},
    },
    [46] = {
        {id=13031, name="Ice Barrier", cost=1300, rank=2, texture="Interface/ICONS/spell_ice_lament", talent = 11426},
        {id=10201, name="Arcane Explosion", cost=26000, rank=5, texture="Interface/ICONS/spell_nature_wispsplode"},
        {id=10197, name="Fire Blast", cost=26000, rank=6, texture="Interface/ICONS/spell_fire_fireball"},
        {id=22782, name="Mage Armor", cost=28000, rank=2, texture="Interface/ICONS/spell_magearmor"},
        {id=10205, name="Scorch", cost=26000, rank=5, texture="Interface/ICONS/spell_fire_soulburn"},
    },
    [48] = {
        {id=12525, name="Pyroblast", cost=1400, rank=6, texture="Interface/ICONS/spell_fire_fireball02", talent = 11366},
        {id=10211, name="Arcane Missiles", cost=28000, rank=6, texture="Interface/ICONS/spell_nature_starfall"},
        {id=10053, name="Conjure Mana Citrine", cost=28000, rank=0, texture="Interface/ICONS/inv_misc_gem_opal_01"},
        {id=10173, name="Dampen Magic", cost=28000, rank=4, texture="Interface/ICONS/spell_nature_abolishmagic"},
        {id=10149, name="Fireball", cost=28000, rank=9, texture="Interface/ICONS/spell_fire_flamebolt"},
        {id=10215, name="Flamestrike", cost=28000, rank=5, texture="Interface/ICONS/spell_fire_selfdestruct"},
    },
    [50] = {
        {id=10160, name="Cone of Cold", cost=32000, rank=4, texture="Interface/ICONS/spell_frost_glacier"},
        {id=10139, name="Conjure Water", cost=32000, rank=6, texture="Interface/ICONS/inv_drink_11"},
        {id=10223, name="Fire Ward", cost=32000, rank=4, texture="Interface/ICONS/spell_fire_firearmor"},
        {id=10180, name="Frostbolt", cost=32000, rank=9, texture="Interface/ICONS/spell_frost_frostbolt02"},
        {id=10219, name="Ice Armor", cost=32000, rank=3, texture="Interface/ICONS/spell_frost_frostarmor02"},
        {id=11419, name="Portal: Darnassus", cost=32000, rank=0, faction="Alliance", texture="Interface/ICONS/spell_arcane_portaldarnassus"},
        {id=11420, name="Portal: Thunder Bluff", cost=32000, rank=0, faction="Horde", texture="Interface/ICONS/spell_arcane_portalthunderbluff"},
        {id=31589, name="Slow", cost=0, rank=0, texture="Interface/ICONS/spell_nature_slow", talent = true},
        {id=31661, name="Dragon's Breath", cost=0, rank=1, texture="Interface/ICONS/inv_misc_head_dragon_01", talent = 31661},
        {id=31687, name="Summon Water Elemental", cost=0, rank=0, texture="Interface/ICONS/spell_frost_summonwaterelemental_2", talent = true},
    },
    [52] = {
        {id=13020, name="Blast Wave", cost=1750, rank=4, texture="Interface/ICONS/spell_holy_excorcism_02", talent = 11113},
        {id=13032, name="Ice Barrier", cost=1750, rank=3, texture="Interface/ICONS/spell_ice_lament", talent = 11426},
        {id=10186, name="Blizzard", cost=35000, rank=5, texture="Interface/ICONS/spell_frost_icestorm"},
        {id=10145, name="Conjure Food", cost=35000, rank=6, texture="Interface/ICONS/inv_misc_food_33"},
        {id=10177, name="Frost Ward", cost=35000, rank=4, texture="Interface/ICONS/spell_frost_frostward"},
        {id=10192, name="Mana Shield", cost=35000, rank=5, texture="Interface/ICONS/spell_shadow_detectlesserinvisibility"},
        {id=10206, name="Scorch", cost=35000, rank=6, texture="Interface/ICONS/spell_fire_soulburn"},
    },
    [54] = {
        {id=12526, name="Pyroblast", cost=1800, rank=7, texture="Interface/ICONS/spell_fire_fireball02", talent = 11366},
        {id=10170, name="Amplify Magic", cost=36000, rank=4, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=10202, name="Arcane Explosion", cost=36000, rank=6, texture="Interface/ICONS/spell_nature_wispsplode"},
        {id=10199, name="Fire Blast", cost=36000, rank=7, texture="Interface/ICONS/spell_fire_fireball"},
        {id=10150, name="Fireball", cost=36000, rank=10, texture="Interface/ICONS/spell_fire_flamebolt"},
        {id=10230, name="Frost Nova", cost=36000, rank=4, texture="Interface/ICONS/spell_frost_frostnova"},
    },
    [56] = {
        {id=33041, name="Dragon's Breath", cost=1900, rank=2, texture="Interface/ICONS/inv_misc_head_dragon_01", talent = 31661},
        {id=23028, name="Arcane Brilliance", cost=38000, rank=1, texture="Interface/ICONS/spell_holy_arcaneintellect"},
        {id=10157, name="Arcane Intellect", cost=38000, rank=5, texture="Interface/ICONS/spell_holy_magicalsentry"},
        {id=10212, name="Arcane Missiles", cost=38000, rank=7, texture="Interface/ICONS/spell_nature_starfall"},
        {id=10216, name="Flamestrike", cost=38000, rank=6, texture="Interface/ICONS/spell_fire_selfdestruct"},
        {id=10181, name="Frostbolt", cost=38000, rank=10, texture="Interface/ICONS/spell_frost_frostbolt02"},
    },
    [58] = {
        {id=13033, name="Ice Barrier", cost=2000, rank=4, texture="Interface/ICONS/spell_ice_lament", talent = 11426},
        {id=10161, name="Cone of Cold", cost=40000, rank=5, texture="Interface/ICONS/spell_frost_glacier"},
        {id=10054, name="Conjure Mana Ruby", cost=40000, rank=0, texture="Interface/ICONS/inv_misc_gem_ruby_01"},
        {id=22783, name="Mage Armor", cost=40000, rank=3, texture="Interface/ICONS/spell_magearmor"},
        {id=10207, name="Scorch", cost=40000, rank=7, texture="Interface/ICONS/spell_fire_soulburn"},
    },
    [60] = {
        {id=13021, name="Blast Wave", cost=2100, rank=5, texture="Interface/ICONS/spell_holy_excorcism_02", talent = 11113},
        {id=18809, name="Pyroblast", cost=2100, rank=8, texture="Interface/ICONS/spell_fire_fireball02", talent = 11366},
        {id=25345, name="Arcane Missiles", cost=42000, rank=8, texture="Interface/ICONS/spell_nature_starfall"},
        {id=10187, name="Blizzard", cost=42000, rank=6, texture="Interface/ICONS/spell_frost_icestorm"},
        {id=28612, name="Conjure Food", cost=42000, rank=7, texture="Interface/ICONS/inv_misc_food_73cinnamonroll"},
        {id=10140, name="Conjure Water", cost=42000, rank=7, texture="Interface/ICONS/inv_drink_18"},
        {id=10174, name="Dampen Magic", cost=42000, rank=5, texture="Interface/ICONS/spell_nature_abolishmagic"},
        {id=10225, name="Fire Ward", cost=42000, rank=5, texture="Interface/ICONS/spell_fire_firearmor"},
        {id=10151, name="Fireball", cost=42000, rank=11, texture="Interface/ICONS/spell_fire_flamebolt"},
        {id=25306, name="Fireball", cost=42000, rank=12, texture="Interface/ICONS/spell_fire_flamebolt"},
        {id=28609, name="Frost Ward", cost=42000, rank=5, texture="Interface/ICONS/spell_frost_frostward"},
        {id=25304, name="Frostbolt", cost=42000, rank=11, texture="Interface/ICONS/spell_frost_frostbolt02"},
        {id=10220, name="Ice Armor", cost=42000, rank=4, texture="Interface/ICONS/spell_frost_frostarmor02"},
        {id=10193, name="Mana Shield", cost=42000, rank=6, texture="Interface/ICONS/spell_shadow_detectlesserinvisibility"},
        {id=12826, name="Polymorph", cost=42000, rank=4, texture="Interface/ICONS/spell_nature_polymorph"},
        {id=28271, name="Polymorph", cost=0, rank=0, texture="Interface/ICONS/ability_hunter_pet_turtle"},
        {id=28272, name="Polymorph", cost=0, rank=0, texture="Interface/ICONS/spell_magic_polymorphpig"},
        {id=33690, name="Teleport: Shattrath", cost=20000, rank=0, faction="Alliance", texture="Interface/ICONS/spell_arcane_teleportshattrath"},
        {id=35715, name="Teleport: Shattrath", cost=20000, rank=0, faction="Horde", texture="Interface/ICONS/spell_arcane_teleportshattrath"},
    },
    [61] = {
        {id=27078, name="Fire Blast", cost=46000, rank=8, texture="Interface/ICONS/spell_fire_fireball"},
    },
    [62] = {
        {id=27080, name="Arcane Explosion", cost=51000, rank=7, texture="Interface/ICONS/spell_nature_wispsplode"},
        {id=30482, name="Molten Armor", cost=51000, rank=1, texture="Interface/ICONS/ability_mage_moltenarmor"},
    },
    [63] = {
        {id=27130, name="Amplify Magic", cost=57000, rank=5, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=27075, name="Arcane Missiles", cost=57000, rank=9, texture="Interface/ICONS/spell_nature_starfall"},
        {id=27071, name="Frostbolt", cost=57000, rank=12, texture="Interface/ICONS/spell_frost_frostbolt02"},
    },
    [64] = {
        {id=33042, name="Dragon's Breath", cost=2200, rank=3, texture="Interface/ICONS/inv_misc_head_dragon_01", talent = 31661},
        {id=27134, name="Ice Barrier", cost=2500, rank=5, texture="Interface/ICONS/spell_ice_lament", talent = 11426},
        {id=30451, name="Arcane Blast", cost=63000, rank=1, texture="Interface/ICONS/spell_arcane_blast"},
        {id=27086, name="Flamestrike", cost=63000, rank=7, texture="Interface/ICONS/spell_fire_selfdestruct"},
    },
    [65] = {
        {id=27133, name="Blast Wave", cost=10500, rank=6, texture="Interface/ICONS/spell_holy_excorcism_02", talent = 11113},
        {id=27087, name="Cone of Cold", cost=70000, rank=6, texture="Interface/ICONS/spell_frost_glacier"},
        {id=37420, name="Conjure Water", cost=70000, rank=8, texture="Interface/ICONS/inv_drink_waterskin_11"},
        {id=33691, name="Portal: Shattrath", cost=150000, rank=0, faction="Alliance", texture="Interface/ICONS/spell_arcane_portalshattrath"},
        {id=35717, name="Portal: Shattrath", cost=150000, rank=0, faction="Horde", texture="Interface/ICONS/spell_arcane_portalshattrath"},
        {id=27073, name="Scorch", cost=70000, rank=8, texture="Interface/ICONS/spell_fire_soulburn"},
    },
    [66] = {
        {id=27132, name="Pyroblast", cost=10500, rank=9, texture="Interface/ICONS/spell_fire_fireball02", talent = 11366},
        {id=27070, name="Fireball", cost=78000, rank=13, texture="Interface/ICONS/spell_fire_flamebolt"},
        {id=30455, name="Ice Lance", cost=78000, rank=1, texture="Interface/ICONS/spell_frost_frostblast"},
    },
    [67] = {
        {id=33944, name="Dampen Magic", cost=87000, rank=6, texture="Interface/ICONS/spell_nature_abolishmagic"},
        {id=27088, name="Frost Nova", cost=87000, rank=5, texture="Interface/ICONS/spell_frost_frostnova"},
    },
    [68] = {
        {id=27085, name="Blizzard", cost=96000, rank=7, texture="Interface/ICONS/spell_frost_icestorm"},
        {id=27101, name="Conjure Mana Emerald", cost=96000, rank=0, texture="Interface/ICONS/inv_misc_gem_stone_01"},
        {id=66, name="Invisibility", cost=96000, rank=0, texture="Interface/ICONS/ability_mage_invisibility"},
        {id=27131, name="Mana Shield", cost=96000, rank=7, texture="Interface/ICONS/spell_shadow_detectlesserinvisibility"},
    },
    [69] = {
        {id=33946, name="Amplify Magic", cost=110000, rank=6, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=38699, name="Arcane Missiles", cost=87000, rank=10, texture="Interface/ICONS/spell_nature_starfall"},
        {id=27128, name="Fire Ward", cost=110000, rank=6, texture="Interface/ICONS/spell_fire_firearmor"},
        {id=27072, name="Frostbolt", cost=110000, rank=13, texture="Interface/ICONS/spell_frost_frostbolt02"},
        {id=27124, name="Ice Armor", cost=110000, rank=5, texture="Interface/ICONS/spell_frost_frostarmor02"},
        {id=27125, name="Mage Armor", cost=110000, rank=4, texture="Interface/ICONS/spell_magearmor"},
    },
    [70] = {
        {id=33933, name="Blast Wave", cost=12500, rank=7, texture="Interface/ICONS/spell_holy_excorcism_02", talent = 11113},
        {id=33043, name="Dragon's Breath", cost=2500, rank=4, texture="Interface/ICONS/inv_misc_head_dragon_01", talent = 31661},
        {id=33405, name="Ice Barrier", cost=10500, rank=6, texture="Interface/ICONS/spell_ice_lament", talent = 11426},
        {id=33938, name="Pyroblast", cost=10500, rank=10, texture="Interface/ICONS/spell_fire_fireball02", talent = 11366},
        {id=27127, name="Arcane Brilliance", cost=0, rank=2, texture="Interface/ICONS/spell_holy_arcaneintellect"},
        {id=27082, name="Arcane Explosion", cost=120000, rank=8, texture="Interface/ICONS/spell_nature_wispsplode"},
        {id=27126, name="Arcane Intellect", cost=120000, rank=6, texture="Interface/ICONS/spell_holy_magicalsentry"},
        {id=38704, name="Arcane Missiles", cost=0, rank=11, texture="Interface/ICONS/spell_nature_starfall"},
        {id=33717, name="Conjure Food", cost=0, rank=8, texture="Interface/ICONS/inv_misc_food_32"},
        {id=27090, name="Conjure Water", cost=0, rank=9, texture="Interface/ICONS/inv_drink_16"},
        {id=27079, name="Fire Blast", cost=120000, rank=9, texture="Interface/ICONS/spell_fire_fireball"},
        {id=38692, name="Fireball", cost=0, rank=14, texture="Interface/ICONS/spell_fire_flamebolt"},
        {id=32796, name="Frost Ward", cost=120000, rank=6, texture="Interface/ICONS/spell_frost_frostward"},
        {id=38697, name="Frostbolt", cost=0, rank=14, texture="Interface/ICONS/spell_frost_frostbolt02"},
        {id=43987, name="Ritual of Refreshment", cost=120000, rank=1, texture="Interface/ICONS/spell_arcane_massdispel"},
        {id=27074, name="Scorch", cost=120000, rank=9, texture="Interface/ICONS/spell_fire_soulburn"},
        {id=30449, name="Spellsteal", cost=120000, rank=0, texture="Interface/ICONS/spell_arcane_arcane02"},
    },
}