local _, TFG = ...

TFG.PRIEST_TBC = {
    [1] = {
        {id=2050, name="Lesser Heal", cost=0, rank=1, texture="Interface/ICONS/spell_holy_lesserheal"},
        {id=1243, name="Power Word: Fortitude", cost=10, rank=1, texture="Interface/ICONS/spell_holy_wordfortitude"},
        {id=585, name="Smite", cost=0, rank=1, texture="Interface/ICONS/spell_holy_holysmite"},
    },
    [4] = {
        {id=2052, name="Lesser Heal", cost=100, rank=2, texture="Interface/ICONS/spell_holy_lesserheal"},
        {id=589, name="Shadow Word: Pain", cost=100, rank=1, texture="Interface/ICONS/spell_shadow_shadowwordpain"},
    },
    [6] = {
        {id=17, name="Power Word: Shield", cost=100, rank=1, texture="Interface/ICONS/spell_holy_powerwordshield"},
        {id=591, name="Smite", cost=100, rank=2, texture="Interface/ICONS/spell_holy_holysmite"},
    },
    [8] = {
        {id=586, name="Fade", cost=200, rank=1, texture="Interface/ICONS/spell_magic_lesserinvisibilty"},
        {id=139, name="Renew", cost=200, rank=1, texture="Interface/ICONS/spell_holy_renew"},
    },
    [10] = {
        {id=13908, name="Desperate Prayer", cost=76, rank=1, race="Dwarf, Human", texture="Interface/ICONS/spell_holy_restoration"},
        {id=9035, name="Hex of Weakness", cost=90, rank=1, race="Troll", texture="Interface/ICONS/spell_shadow_fingerofdeath"},
        {id=2053, name="Lesser Heal", cost=300, rank=3, texture="Interface/ICONS/spell_holy_lesserheal"},
        {id=8092, name="Mind Blast", cost=300, rank=1, texture="Interface/ICONS/spell_shadow_unholyfrenzy"},
        {id=2006, name="Resurrection", cost=300, rank=1, texture="Interface/ICONS/spell_holy_resurrection"},
        {id=594, name="Shadow Word: Pain", cost=300, rank=2, texture="Interface/ICONS/spell_shadow_shadowwordpain"},
        {id=10797, name="Starshards", cost=90, rank=1, race="Night Elf", texture="Interface/ICONS/spell_arcane_starfire"},
        {id=32548, name="Symbol of Hope", cost=100, rank=0, race="Draenei", texture="Interface/ICONS/spell_holy_symbolofhope"},
        {id=2652, name="Touch of Weakness", cost=90, rank=1, race="Undead, Blood Elf", texture="Interface/ICONS/spell_shadow_deadofnight"},
    },
    [12] = {
        {id=588, name="Inner Fire", cost=800, rank=1, texture="Interface/ICONS/spell_holy_innerfire"},
        {id=1244, name="Power Word: Fortitude", cost=800, rank=2, texture="Interface/ICONS/spell_holy_wordfortitude"},
        {id=592, name="Power Word: Shield", cost=800, rank=2, texture="Interface/ICONS/spell_holy_powerwordshield"},
    },
    [14] = {
        {id=528, name="Cure Disease", cost=1200, rank=0, texture="Interface/ICONS/spell_holy_nullifydisease"},
        {id=8122, name="Psychic Scream", cost=1200, rank=1, texture="Interface/ICONS/spell_shadow_psychicscream"},
        {id=6074, name="Renew", cost=1200, rank=2, texture="Interface/ICONS/spell_holy_renew"},
        {id=598, name="Smite", cost=1200, rank=3, texture="Interface/ICONS/spell_holy_holysmite"},
    },
    [16] = {
        {id=2054, name="Heal", cost=1600, rank=1, texture="Interface/ICONS/spell_holy_heal"},
        {id=8102, name="Mind Blast", cost=1600, rank=2, texture="Interface/ICONS/spell_shadow_unholyfrenzy"},
    },
    [18] = {
        {id=19236, name="Desperate Prayer", cost=100, rank=2, race="Dwarf, Human", texture="Interface/ICONS/spell_holy_restoration"},
        {id=527, name="Dispel Magic", cost=2000, rank=1, texture="Interface/ICONS/spell_holy_dispelmagic"},
        {id=600, name="Power Word: Shield", cost=2000, rank=3, texture="Interface/ICONS/spell_holy_powerwordshield"},
        {id=970, name="Shadow Word: Pain", cost=2000, rank=3, texture="Interface/ICONS/spell_shadow_shadowwordpain"},
        {id=19296, name="Starshards", cost=100, rank=2, race="Night Elf", texture="Interface/ICONS/spell_arcane_starfire"},
    },
    [20] = {
        {id=44041, name="Chastise", cost=100, rank=1, race="Draenei", texture="Interface/ICONS/spell_holy_chastise"},
        {id=32676, name="Consume Magic", cost=100, rank=0, race="Blood Elf", texture="Interface/ICONS/spell_arcane_studentofmagic"},
        {id=2944, name="Devouring Plague", cost=100, rank=1, race="Undead", texture="Interface/ICONS/spell_shadow_blackplague"},
        {id=2651, name="Elune's Grace", cost=100, rank=0, race="Night Elf", texture="Interface/ICONS/spell_holy_elunesgrace"},
        {id=9578, name="Fade", cost=3000, rank=2, texture="Interface/ICONS/spell_magic_lesserinvisibilty"},
        {id=6346, name="Fear Ward", cost=800, rank=0, texture="Interface/ICONS/spell_holy_excorcism"},
        {id=13896, name="Feedback", cost=100, rank=1, race="Human", texture="Interface/ICONS/spell_shadow_ritualofsacrifice"},
        {id=2061, name="Flash Heal", cost=3000, rank=1, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=19281, name="Hex of Weakness", cost=150, rank=2, race="Troll", texture="Interface/ICONS/spell_shadow_fingerofdeath"},
        {id=14914, name="Holy Fire", cost=3000, rank=1, texture="Interface/ICONS/spell_holy_searinglight"},
        {id=7128, name="Inner Fire", cost=3000, rank=2, texture="Interface/ICONS/spell_holy_innerfire"},
        {id=453, name="Mind Soothe", cost=3000, rank=1, texture="Interface/ICONS/spell_holy_mindsooth"},
        {id=6075, name="Renew", cost=3000, rank=3, texture="Interface/ICONS/spell_holy_renew"},
        {id=9484, name="Shackle Undead", cost=3000, rank=1, texture="Interface/ICONS/spell_nature_slow"},
        {id=18137, name="Shadowguard", cost=100, rank=1, race="Troll", texture="Interface/ICONS/spell_nature_lightningshield"},
        {id=19261, name="Touch of Weakness", cost=150, rank=2, race="Undead, Blood Elf", texture="Interface/ICONS/spell_shadow_deadofnight"},
        {id=14751, name="Inner Focus", cost=0, rank=0, texture="Interface/ICONS/spell_frost_windwalkon", talent = true},
        {id=15237, name="Holy Nova", cost=0, rank=1, texture="Interface/ICONS/spell_holy_holynova", talent = 15237},
        {id=15407, name="Mind Flay", cost=0, rank=1, texture="Interface/ICONS/spell_shadow_siphonmana", talent = 15407},
    },
    [22] = {
        {id=2055, name="Heal", cost=4000, rank=2, texture="Interface/ICONS/spell_holy_heal"},
        {id=8103, name="Mind Blast", cost=4000, rank=3, texture="Interface/ICONS/spell_shadow_unholyfrenzy"},
        {id=2096, name="Mind Vision", cost=4000, rank=1, texture="Interface/ICONS/spell_holy_mindvision"},
        {id=2010, name="Resurrection", cost=4000, rank=2, texture="Interface/ICONS/spell_holy_resurrection"},
        {id=984, name="Smite", cost=4000, rank=4, texture="Interface/ICONS/spell_holy_holysmite"},
    },
    [24] = {
        {id=15262, name="Holy Fire", cost=5000, rank=2, texture="Interface/ICONS/spell_holy_searinglight"},
        {id=8129, name="Mana Burn", cost=5000, rank=1, texture="Interface/ICONS/spell_shadow_manaburn"},
        {id=1245, name="Power Word: Fortitude", cost=5000, rank=3, texture="Interface/ICONS/spell_holy_wordfortitude"},
        {id=3747, name="Power Word: Shield", cost=5000, rank=4, texture="Interface/ICONS/spell_holy_powerwordshield"},
    },
    [26] = {
        {id=19238, name="Desperate Prayer", cost=300, rank=3, race="Dwarf, Human", texture="Interface/ICONS/spell_holy_restoration"},
        {id=9472, name="Flash Heal", cost=6000, rank=2, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=6076, name="Renew", cost=6000, rank=4, texture="Interface/ICONS/spell_holy_renew"},
        {id=992, name="Shadow Word: Pain", cost=6000, rank=4, texture="Interface/ICONS/spell_shadow_shadowwordpain"},
        {id=19299, name="Starshards", cost=300, rank=3, race="Night Elf", texture="Interface/ICONS/spell_arcane_starfire"},
    },
    [28] = {
        {id=15430, name="Holy Nova", cost=400, rank=2, texture="Interface/ICONS/spell_holy_holynova", talent = 15237},
        {id=17311, name="Mind Flay", cost=400, rank=2, texture="Interface/ICONS/spell_shadow_siphonmana", talent = 15407},
        {id=19276, name="Devouring Plague", cost=400, rank=2, race="Undead", texture="Interface/ICONS/spell_shadow_blackplague"},
        {id=6063, name="Heal", cost=8000, rank=3, texture="Interface/ICONS/spell_holy_heal02"},
        {id=8104, name="Mind Blast", cost=8000, rank=4, texture="Interface/ICONS/spell_shadow_unholyfrenzy"},
        {id=8124, name="Psychic Scream", cost=8000, rank=2, texture="Interface/ICONS/spell_shadow_psychicscream"},
        {id=19308, name="Shadowguard", cost=400, rank=2, race="Troll", texture="Interface/ICONS/spell_nature_lightningshield"},
    },
    [30] = {
        {id=44043, name="Chastise", cost=500, rank=2, race="Draenei", texture="Interface/ICONS/spell_holy_chastise"},
        {id=9579, name="Fade", cost=10000, rank=3, texture="Interface/ICONS/spell_magic_lesserinvisibilty"},
        {id=19271, name="Feedback", cost=500, rank=2, race="Human", texture="Interface/ICONS/spell_shadow_ritualofsacrifice"},
        {id=19282, name="Hex of Weakness", cost=500, rank=3, race="Troll", texture="Interface/ICONS/spell_shadow_fingerofdeath"},
        {id=15263, name="Holy Fire", cost=10000, rank=3, texture="Interface/ICONS/spell_holy_searinglight"},
        {id=602, name="Inner Fire", cost=10000, rank=3, texture="Interface/ICONS/spell_holy_innerfire"},
        {id=605, name="Mind Control", cost=10000, rank=1, texture="Interface/ICONS/spell_shadow_shadowworddominate"},
        {id=6065, name="Power Word: Shield", cost=10000, rank=5, texture="Interface/ICONS/spell_holy_powerwordshield"},
        {id=596, name="Prayer of Healing", cost=10000, rank=1, texture="Interface/ICONS/spell_holy_prayerofhealing02"},
        {id=976, name="Shadow Protection", cost=10000, rank=1, texture="Interface/ICONS/spell_shadow_antishadow"},
        {id=1004, name="Smite", cost=10000, rank=5, texture="Interface/ICONS/spell_holy_holysmite"},
        {id=19262, name="Touch of Weakness", cost=500, rank=3, race="Undead, Blood Elf", texture="Interface/ICONS/spell_shadow_deadofnight"},
        {id=14752, name="Divine Spirit", cost=0, rank=1, texture="Interface/ICONS/spell_holy_divinespirit", talent = 14752},
        {id=15487, name="Silence", cost=0, rank=0, texture="Interface/ICONS/spell_shadow_impphaseshift", talent = true},
        {id=15286, name="Vampiric Embrace", cost=0, rank=0, texture="Interface/ICONS/spell_shadow_unsummonbuilding", talent = true},
    },
    [32] = {
        {id=552, name="Abolish Disease", cost=11000, rank=0, texture="Interface/ICONS/spell_nature_nullifydisease"},
        {id=9473, name="Flash Heal", cost=11000, rank=3, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=8131, name="Mana Burn", cost=11000, rank=2, texture="Interface/ICONS/spell_shadow_manaburn"},
        {id=6077, name="Renew", cost=11000, rank=5, texture="Interface/ICONS/spell_holy_renew"},
    },
    [34] = {
        {id=19240, name="Desperate Prayer", cost=600, rank=4, race="Dwarf, Human", texture="Interface/ICONS/spell_holy_restoration"},
        {id=6064, name="Heal", cost=12000, rank=4, texture="Interface/ICONS/spell_holy_heal02"},
        {id=1706, name="Levitate", cost=12000, rank=0, texture="Interface/ICONS/spell_holy_layonhands"},
        {id=8105, name="Mind Blast", cost=12000, rank=5, texture="Interface/ICONS/spell_shadow_unholyfrenzy"},
        {id=10880, name="Resurrection", cost=12000, rank=3, texture="Interface/ICONS/spell_holy_resurrection"},
        {id=2767, name="Shadow Word: Pain", cost=12000, rank=5, texture="Interface/ICONS/spell_shadow_shadowwordpain"},
        {id=19302, name="Starshards", cost=600, rank=4, race="Night Elf", texture="Interface/ICONS/spell_arcane_starfire"},
    },
    [36] = {
        {id=15431, name="Holy Nova", cost=700, rank=3, texture="Interface/ICONS/spell_holy_holynova", talent = 15237},
        {id=17312, name="Mind Flay", cost=700, rank=3, texture="Interface/ICONS/spell_shadow_siphonmana", talent = 15407},
        {id=19277, name="Devouring Plague", cost=700, rank=3, race="Undead", texture="Interface/ICONS/spell_shadow_blackplague"},
        {id=988, name="Dispel Magic", cost=14000, rank=2, texture="Interface/ICONS/spell_holy_dispelmagic"},
        {id=15264, name="Holy Fire", cost=14000, rank=4, texture="Interface/ICONS/spell_holy_searinglight"},
        {id=8192, name="Mind Soothe", cost=14000, rank=2, texture="Interface/ICONS/spell_holy_mindsooth"},
        {id=2791, name="Power Word: Fortitude", cost=14000, rank=4, texture="Interface/ICONS/spell_holy_wordfortitude"},
        {id=6066, name="Power Word: Shield", cost=14000, rank=6, texture="Interface/ICONS/spell_holy_powerwordshield"},
        {id=19309, name="Shadowguard", cost=700, rank=3, race="Troll", texture="Interface/ICONS/spell_nature_lightningshield"},
    },
    [38] = {
        {id=9474, name="Flash Heal", cost=16000, rank=4, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=6078, name="Renew", cost=16000, rank=6, texture="Interface/ICONS/spell_holy_renew"},
        {id=6060, name="Smite", cost=16000, rank=6, texture="Interface/ICONS/spell_holy_holysmite"},
    },
    [40] = {
        {id=14818, name="Divine Spirit", cost=900, rank=2, texture="Interface/ICONS/spell_holy_divinespirit", talent = 14752},
        {id=44044, name="Chastise", cost=900, rank=3, race="Draenei", texture="Interface/ICONS/spell_holy_chastise"},
        {id=9592, name="Fade", cost=18000, rank=4, texture="Interface/ICONS/spell_magic_lesserinvisibilty"},
        {id=19273, name="Feedback", cost=900, rank=3, race="Human", texture="Interface/ICONS/spell_shadow_ritualofsacrifice"},
        {id=2060, name="Greater Heal", cost=18000, rank=1, texture="Interface/ICONS/spell_holy_greaterheal"},
        {id=19283, name="Hex of Weakness", cost=900, rank=4, race="Troll", texture="Interface/ICONS/spell_shadow_fingerofdeath"},
        {id=1006, name="Inner Fire", cost=18000, rank=4, texture="Interface/ICONS/spell_holy_innerfire"},
        {id=10874, name="Mana Burn", cost=18000, rank=3, texture="Interface/ICONS/spell_shadow_manaburn"},
        {id=8106, name="Mind Blast", cost=18000, rank=6, texture="Interface/ICONS/spell_shadow_unholyfrenzy"},
        {id=996, name="Prayer of Healing", cost=18000, rank=2, texture="Interface/ICONS/spell_holy_prayerofhealing02"},
        {id=9485, name="Shackle Undead", cost=18000, rank=2, texture="Interface/ICONS/spell_nature_slow"},
        {id=19264, name="Touch of Weakness", cost=900, rank=4, race="Undead, Blood Elf", texture="Interface/ICONS/spell_shadow_deadofnight"},
        {id=10060, name="Power Infusion", cost=0, rank=0, texture="Interface/ICONS/spell_holy_powerinfusion", talent = true},
        {id=724, name="Lightwell", cost=0, rank=1, texture="Interface/ICONS/spell_holy_summonlightwell", talent = 724},
        {id=15473, name="Shadowform", cost=0, rank=0, texture="Interface/ICONS/spell_shadow_shadowform", talent = true},
    },
    [42] = {
        {id=19241, name="Desperate Prayer", cost=1100, rank=5, race="Dwarf, Human", texture="Interface/ICONS/spell_holy_restoration"},
        {id=15265, name="Holy Fire", cost=22000, rank=5, texture="Interface/ICONS/spell_holy_searinglight"},
        {id=10898, name="Power Word: Shield", cost=22000, rank=7, texture="Interface/ICONS/spell_holy_powerwordshield"},
        {id=10888, name="Psychic Scream", cost=22000, rank=3, texture="Interface/ICONS/spell_shadow_psychicscream"},
        {id=10957, name="Shadow Protection", cost=22000, rank=2, texture="Interface/ICONS/spell_shadow_antishadow"},
        {id=10892, name="Shadow Word: Pain", cost=22000, rank=6, texture="Interface/ICONS/spell_shadow_shadowwordpain"},
        {id=19303, name="Starshards", cost=1100, rank=5, race="Night Elf", texture="Interface/ICONS/spell_arcane_starfire"},
    },
    [44] = {
        {id=27799, name="Holy Nova", cost=1200, rank=4, texture="Interface/ICONS/spell_holy_holynova", talent = 15237},
        {id=17313, name="Mind Flay", cost=1200, rank=4, texture="Interface/ICONS/spell_shadow_siphonmana", talent = 15407},
        {id=19278, name="Devouring Plague", cost=1200, rank=4, race="Undead", texture="Interface/ICONS/spell_shadow_blackplague"},
        {id=10915, name="Flash Heal", cost=24000, rank=5, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=10911, name="Mind Control", cost=24000, rank=2, texture="Interface/ICONS/spell_shadow_shadowworddominate"},
        {id=10909, name="Mind Vision", cost=24000, rank=2, texture="Interface/ICONS/spell_holy_mindvision"},
        {id=10927, name="Renew", cost=24000, rank=7, texture="Interface/ICONS/spell_holy_renew"},
        {id=19310, name="Shadowguard", cost=1200, rank=4, race="Troll", texture="Interface/ICONS/spell_nature_lightningshield"},
    },
    [46] = {
        {id=10963, name="Greater Heal", cost=26000, rank=2, texture="Interface/ICONS/spell_holy_greaterheal"},
        {id=10945, name="Mind Blast", cost=26000, rank=7, texture="Interface/ICONS/spell_shadow_unholyfrenzy"},
        {id=10881, name="Resurrection", cost=26000, rank=4, texture="Interface/ICONS/spell_holy_resurrection"},
        {id=10933, name="Smite", cost=26000, rank=7, texture="Interface/ICONS/spell_holy_holysmite"},
    },
    [48] = {
        {id=15266, name="Holy Fire", cost=28000, rank=6, texture="Interface/ICONS/spell_holy_searinglight"},
        {id=10875, name="Mana Burn", cost=28000, rank=4, texture="Interface/ICONS/spell_shadow_manaburn"},
        {id=10937, name="Power Word: Fortitude", cost=28000, rank=5, texture="Interface/ICONS/spell_holy_wordfortitude"},
        {id=10899, name="Power Word: Shield", cost=28000, rank=8, texture="Interface/ICONS/spell_holy_powerwordshield"},
        {id=21562, name="Prayer of Fortitude", cost=28000, rank=1, texture="Interface/ICONS/spell_holy_prayeroffortitude"},
    },
    [50] = {
        {id=14819, name="Divine Spirit", cost=1500, rank=3, texture="Interface/ICONS/spell_holy_divinespirit", talent = 14752},
        {id=27870, name="Lightwell", cost=1200, rank=2, texture="Interface/ICONS/spell_holy_summonlightwell", talent = 724},
        {id=44045, name="Chastise", cost=1500, rank=4, race="Draenei", texture="Interface/ICONS/spell_holy_chastise"},
        {id=19242, name="Desperate Prayer", cost=1500, rank=6, race="Dwarf, Human", texture="Interface/ICONS/spell_holy_restoration"},
        {id=10941, name="Fade", cost=30000, rank=5, texture="Interface/ICONS/spell_magic_lesserinvisibilty"},
        {id=19274, name="Feedback", cost=1500, rank=4, race="Human", texture="Interface/ICONS/spell_shadow_ritualofsacrifice"},
        {id=10916, name="Flash Heal", cost=30000, rank=6, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=19284, name="Hex of Weakness", cost=1500, rank=5, race="Troll", texture="Interface/ICONS/spell_shadow_fingerofdeath"},
        {id=10951, name="Inner Fire", cost=30000, rank=5, texture="Interface/ICONS/spell_holy_innerfire"},
        {id=10960, name="Prayer of Healing", cost=30000, rank=3, texture="Interface/ICONS/spell_holy_prayerofhealing02"},
        {id=10928, name="Renew", cost=30000, rank=8, texture="Interface/ICONS/spell_holy_renew"},
        {id=10893, name="Shadow Word: Pain", cost=30000, rank=7, texture="Interface/ICONS/spell_shadow_shadowwordpain"},
        {id=19304, name="Starshards", cost=1500, rank=6, race="Night Elf", texture="Interface/ICONS/spell_arcane_starfire"},
        {id=19265, name="Touch of Weakness", cost=1500, rank=5, race="Undead, Blood Elf", texture="Interface/ICONS/spell_shadow_deadofnight"},
        {id=33206, name="Pain Suppression", cost=0, rank=0, texture="Interface/ICONS/spell_holy_painsupression", talent = true},
        {id=34861, name="Circle of Healing", cost=0, rank=1, texture="Interface/ICONS/spell_holy_circleofrenewal", talent = 34861},
        {id=34914, name="Vampiric Touch", cost=0, rank=1, texture="Interface/ICONS/spell_holy_stoicism", talent = 34914},
    },
    [52] = {
        {id=27800, name="Holy Nova", cost=1900, rank=5, texture="Interface/ICONS/spell_holy_holynova", talent = 15237},
        {id=17314, name="Mind Flay", cost=1900, rank=5, texture="Interface/ICONS/spell_shadow_siphonmana", talent = 15407},
        {id=19279, name="Devouring Plague", cost=1900, rank=5, race="Undead", texture="Interface/ICONS/spell_shadow_blackplague"},
        {id=10964, name="Greater Heal", cost=38000, rank=3, texture="Interface/ICONS/spell_holy_greaterheal"},
        {id=10946, name="Mind Blast", cost=38000, rank=8, texture="Interface/ICONS/spell_shadow_unholyfrenzy"},
        {id=10953, name="Mind Soothe", cost=38000, rank=3, texture="Interface/ICONS/spell_holy_mindsooth"},
        {id=19311, name="Shadowguard", cost=1900, rank=5, race="Troll", texture="Interface/ICONS/spell_nature_lightningshield"},
    },
    [54] = {
        {id=15267, name="Holy Fire", cost=40000, rank=7, texture="Interface/ICONS/spell_holy_searinglight"},
        {id=10900, name="Power Word: Shield", cost=40000, rank=9, texture="Interface/ICONS/spell_holy_powerwordshield"},
        {id=10934, name="Smite", cost=40000, rank=8, texture="Interface/ICONS/spell_holy_holysmite"},
    },
    [56] = {
        {id=34863, name="Circle of Healing", cost=2100, rank=2, texture="Interface/ICONS/spell_holy_circleofrenewal", talent = 34861},
        {id=10917, name="Flash Heal", cost=42000, rank=7, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=10876, name="Mana Burn", cost=42000, rank=5, texture="Interface/ICONS/spell_shadow_manaburn"},
        {id=27683, name="Prayer of Shadow Protection", cost=42000, rank=1, texture="Interface/ICONS/spell_holy_prayerofshadowprotection"},
        {id=10890, name="Psychic Scream", cost=42000, rank=4, texture="Interface/ICONS/spell_shadow_psychicscream"},
        {id=10929, name="Renew", cost=42000, rank=9, texture="Interface/ICONS/spell_holy_renew"},
        {id=10958, name="Shadow Protection", cost=42000, rank=3, texture="Interface/ICONS/spell_shadow_antishadow"},
    },
    [58] = {
        {id=19243, name="Desperate Prayer", cost=2200, rank=7, race="Dwarf, Human", texture="Interface/ICONS/spell_holy_restoration"},
        {id=10965, name="Greater Heal", cost=44000, rank=4, texture="Interface/ICONS/spell_holy_greaterheal"},
        {id=10947, name="Mind Blast", cost=44000, rank=9, texture="Interface/ICONS/spell_shadow_unholyfrenzy"},
        {id=10912, name="Mind Control", cost=44000, rank=3, texture="Interface/ICONS/spell_shadow_shadowworddominate"},
        {id=20770, name="Resurrection", cost=44000, rank=5, texture="Interface/ICONS/spell_holy_resurrection"},
        {id=10894, name="Shadow Word: Pain", cost=44000, rank=8, texture="Interface/ICONS/spell_shadow_shadowwordpain"},
        {id=19305, name="Starshards", cost=2200, rank=7, race="Night Elf", texture="Interface/ICONS/spell_arcane_starfire"},
    },
    [60] = {
        {id=34864, name="Circle of Healing", cost=2300, rank=3, texture="Interface/ICONS/spell_holy_circleofrenewal", talent = 34861},
        {id=27841, name="Divine Spirit", cost=2300, rank=4, texture="Interface/ICONS/spell_holy_divinespirit", talent = 14752},
        {id=27801, name="Holy Nova", cost=2300, rank=6, texture="Interface/ICONS/spell_holy_holynova", talent = 15237},
        {id=27871, name="Lightwell", cost=1500, rank=3, texture="Interface/ICONS/spell_holy_summonlightwell", talent = 724},
        {id=18807, name="Mind Flay", cost=2300, rank=6, texture="Interface/ICONS/spell_shadow_siphonmana", talent = 15407},
        {id=34916, name="Vampiric Touch", cost=2300, rank=2, texture="Interface/ICONS/spell_holy_stoicism", talent = 34914},
        {id=44046, name="Chastise", cost=2300, rank=5, race="Draenei", texture="Interface/ICONS/spell_holy_chastise"},
        {id=19280, name="Devouring Plague", cost=2300, rank=6, race="Undead", texture="Interface/ICONS/spell_shadow_blackplague"},
        {id=10942, name="Fade", cost=46000, rank=6, texture="Interface/ICONS/spell_magic_lesserinvisibilty"},
        {id=19275, name="Feedback", cost=2300, rank=5, race="Human", texture="Interface/ICONS/spell_shadow_ritualofsacrifice"},
        {id=25314, name="Greater Heal", cost=65000, rank=5, texture="Interface/ICONS/spell_holy_greaterheal"},
        {id=19285, name="Hex of Weakness", cost=2300, rank=6, race="Troll", texture="Interface/ICONS/spell_shadow_fingerofdeath"},
        {id=15261, name="Holy Fire", cost=46000, rank=8, texture="Interface/ICONS/spell_holy_searinglight"},
        {id=10952, name="Inner Fire", cost=46000, rank=6, texture="Interface/ICONS/spell_holy_innerfire"},
        {id=10938, name="Power Word: Fortitude", cost=46000, rank=6, texture="Interface/ICONS/spell_holy_wordfortitude"},
        {id=10901, name="Power Word: Shield", cost=46000, rank=10, texture="Interface/ICONS/spell_holy_powerwordshield"},
        {id=21564, name="Prayer of Fortitude", cost=46000, rank=2, texture="Interface/ICONS/spell_holy_prayeroffortitude"},
        {id=10961, name="Prayer of Healing", cost=46000, rank=4, texture="Interface/ICONS/spell_holy_prayerofhealing02"},
        {id=25316, name="Prayer of Healing", cost=6500, rank=5, texture="Interface/ICONS/spell_holy_prayerofhealing02"},
        {id=27681, name="Prayer of Spirit", cost=2300, rank=1, texture="Interface/ICONS/spell_holy_prayerofspirit"},
        {id=25315, name="Renew", cost=6500, rank=10, texture="Interface/ICONS/spell_holy_renew"},
        {id=10955, name="Shackle Undead", cost=46000, rank=3, texture="Interface/ICONS/spell_nature_slow"},
        {id=19312, name="Shadowguard", cost=2300, rank=6, race="Troll", texture="Interface/ICONS/spell_nature_lightningshield"},
        {id=19266, name="Touch of Weakness", cost=2300, rank=6, race="Undead, Blood Elf", texture="Interface/ICONS/spell_shadow_deadofnight"},
    },
    [61] = {
        {id=25233, name="Flash Heal", cost=53000, rank=8, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=25363, name="Smite", cost=53000, rank=9, texture="Interface/ICONS/spell_holy_holysmite"},
    },
    [62] = {
        {id=32379, name="Shadow Word: Death", cost=59000, rank=1, texture="Interface/ICONS/spell_shadow_demonicfortitude"},
    },
    [63] = {
        {id=25210, name="Greater Heal", cost=65000, rank=6, texture="Interface/ICONS/spell_holy_greaterheal"},
        {id=25379, name="Mana Burn", cost=65000, rank=6, texture="Interface/ICONS/spell_shadow_manaburn"},
        {id=25372, name="Mind Blast", cost=65000, rank=10, texture="Interface/ICONS/spell_shadow_unholyfrenzy"},
    },
    [64] = {
        {id=32546, name="Binding Heal", cost=72000, rank=1, texture="Interface/ICONS/spell_holy_blindingheal"},
    },
    [65] = {
        {id=34865, name="Circle of Healing", cost=2300, rank=4, texture="Interface/ICONS/spell_holy_circleofrenewal", talent = 34861},
        {id=25217, name="Power Word: Shield", cost=80000, rank=11, texture="Interface/ICONS/spell_holy_powerwordshield"},
        {id=25221, name="Renew", cost=80000, rank=11, texture="Interface/ICONS/spell_holy_renew"},
        {id=25367, name="Shadow Word: Pain", cost=80000, rank=9, texture="Interface/ICONS/spell_shadow_shadowwordpain"},
    },
    [66] = {
        {id=25437, name="Desperate Prayer", cost=6500, rank=8, race="Dwarf, Human", texture="Interface/ICONS/spell_holy_restoration"},
        {id=25429, name="Fade", cost=89000, rank=7, texture="Interface/ICONS/spell_magic_lesserinvisibilty"},
        {id=25384, name="Holy Fire", cost=65000, rank=9, texture="Interface/ICONS/spell_holy_searinglight"},
        {id=34433, name="Shadowfiend", cost=89000, rank=1, texture="Interface/ICONS/spell_shadow_shadowfiend"},
        {id=25446, name="Starshards", cost=6500, rank=8, race="Night Elf", texture="Interface/ICONS/spell_arcane_starfire"},
    },
    [67] = {
        {id=25235, name="Flash Heal", cost=99000, rank=9, texture="Interface/ICONS/spell_holy_flashheal"},
        {id=25596, name="Mind Soothe", cost=99000, rank=4, texture="Interface/ICONS/spell_holy_mindsooth"},
    },
    [68] = {
        {id=25331, name="Holy Nova", cost=3250, rank=7, texture="Interface/ICONS/spell_holy_holynova", talent = 15237},
        {id=25387, name="Mind Flay", cost=6500, rank=7, texture="Interface/ICONS/spell_shadow_siphonmana", talent = 15407},
        {id=25467, name="Devouring Plague", cost=6500, rank=7, race="Undead", texture="Interface/ICONS/spell_shadow_blackplague"},
        {id=25213, name="Greater Heal", cost=110000, rank=7, texture="Interface/ICONS/spell_holy_greaterheal"},
        {id=25308, name="Prayer of Healing", cost=110000, rank=6, texture="Interface/ICONS/spell_holy_prayerofhealing02"},
        {id=33076, name="Prayer of Mending", cost=110000, rank=1, texture="Interface/ICONS/spell_holy_prayerofmendingtga"},
        {id=25435, name="Resurrection", cost=110000, rank=6, texture="Interface/ICONS/spell_holy_resurrection"},
        {id=25433, name="Shadow Protection", cost=110000, rank=4, texture="Interface/ICONS/spell_shadow_antishadow"},
        {id=25477, name="Shadowguard", cost=6500, rank=7, race="Troll", texture="Interface/ICONS/spell_nature_lightningshield"},
    },
    [69] = {
        {id=25431, name="Inner Fire", cost=65000, rank=7, texture="Interface/ICONS/spell_holy_innerfire"},
        {id=25375, name="Mind Blast", cost=65000, rank=11, texture="Interface/ICONS/spell_shadow_unholyfrenzy"},
        {id=25364, name="Smite", cost=65000, rank=10, texture="Interface/ICONS/spell_holy_holysmite"},
    },
    [70] = {
        {id=34866, name="Circle of Healing", cost=2300, rank=5, texture="Interface/ICONS/spell_holy_circleofrenewal", talent = 34861},
        {id=25312, name="Divine Spirit", cost=2300, rank=5, texture="Interface/ICONS/spell_holy_divinespirit", talent = 14752},
        {id=28275, name="Lightwell", cost=1500, rank=4, texture="Interface/ICONS/spell_holy_summonlightwell", talent = 724},
        {id=34917, name="Vampiric Touch", cost=2300, rank=3, texture="Interface/ICONS/spell_holy_stoicism", talent = 34914},
        {id=44047, name="Chastise", cost=2762, rank=6, race="Draenei", texture="Interface/ICONS/spell_holy_chastise"},
        {id=25441, name="Feedback", cost=6500, rank=6, race="Human", texture="Interface/ICONS/spell_shadow_ritualofsacrifice"},
        {id=25470, name="Hex of Weakness", cost=6500, rank=7, race="Troll", texture="Interface/ICONS/spell_shadow_fingerofdeath"},
        {id=25380, name="Mana Burn", cost=110000, rank=7, texture="Interface/ICONS/spell_shadow_manaburn"},
        {id=32375, name="Mass Dispel", cost=110000, rank=0, texture="Interface/ICONS/spell_arcane_massdispel"},
        {id=25389, name="Power Word: Fortitude", cost=65000, rank=7, texture="Interface/ICONS/spell_holy_wordfortitude"},
        {id=25218, name="Power Word: Shield", cost=140000, rank=12, texture="Interface/ICONS/spell_holy_powerwordshield"},
        {id=25392, name="Prayer of Fortitude", cost=0, rank=3, texture="Interface/ICONS/spell_holy_prayeroffortitude"},
        {id=39374, name="Prayer of Shadow Protection", cost=0, rank=2, texture="Interface/ICONS/spell_holy_prayerofshadowprotection"},
        {id=32999, name="Prayer of Spirit", cost=3400, rank=2, texture="Interface/ICONS/spell_holy_prayerofspirit"},
        {id=25222, name="Renew", cost=140000, rank=12, texture="Interface/ICONS/spell_holy_renew"},
        {id=32996, name="Shadow Word: Death", cost=110000, rank=2, texture="Interface/ICONS/spell_shadow_demonicfortitude"},
        {id=25368, name="Shadow Word: Pain", cost=140000, rank=10, texture="Interface/ICONS/spell_shadow_shadowwordpain"},
        {id=25461, name="Touch of Weakness", cost=6500, rank=7, race="Undead, Blood Elf", texture="Interface/ICONS/spell_shadow_deadofnight"},
    },
}
