local _, TFG = ...

TFG.ENGINEERING_VANILLA = {
    [1] = {
        {
            spell_id = 3918,
            name = "Rough Blasting Powder",
            icon = "inv_misc_dust_01",
            source = {
                type = "Trainer",
            },
            product = { item_id = 4357, qty = 1 },
            materials = {
                { item_id = 2835, qty = 1 },
            },
            levels = { 1, 20, 30, 40 },
        },
        {
            spell_id = 3919,
            name = "Rough Dynamite",
            icon = "inv_misc_bomb_06",
            source = {
                type = "Trainer",
            },
            product = { item_id = 4358, qty = 2 },
            materials = {
                { item_id = 4357, qty = 2 },
                { item_id = 2589, qty = 1 },
            },
            levels = { 1, 30, 45, 60 },
        },
        {
            spell_id = 4036,
            name = "Engineering",
            icon = "trade_engineering",
            source = {
                type = "Trainer",
            },
        },
        {
            spell_id = 20219,
            name = "Gnomish Engineer",
            icon = "inv_gizmo_02",
            source = {
                type = "Trainer",
            },
        },
        {
            spell_id = 20222,
            name = "Goblin Engineer",
            icon = "spell_fire_selfdestruct",
            source = {
                type = "Trainer",
            },
        },
    },
    [30] = {
        {
            spell_id = 3922,
            name = "Handful of Copper Bolts",
            icon = "inv_misc_gear_06",
            source = {
                type = "Trainer",
                cost = 115,
            },
            product = { item_id = 4359, qty = 1 },
            materials = {
                { item_id = 2840, qty = 1 },
            },
            levels = { 30, 45, 52, 60 },
        },
        {
            spell_id = 3923,
            name = "Rough Copper Bomb",
            icon = "inv_misc_bomb_09",
            source = {
                type = "Trainer",
                cost = 130,
            },
            product = { item_id = 4360, qty = 2 },
            materials = {
                { item_id = 2840, qty = 1 },
                { item_id = 4359, qty = 1 },
                { item_id = 4357, qty = 2 },
                { item_id = 2589, qty = 1 },
            },
            levels = { 30, 60, 75, 90 },
        },
        {
            spell_id = 3920,
            name = "Crafted Light Shot",
            icon = "inv_ammo_bullet_02",
            source = {
                type = "Trainer",
            },
            product = { item_id = 8067, qty = 200 },
            materials = {
                { item_id = 4357, qty = 1 },
                { item_id = 2840, qty = 1 },
            },
            levels = { 1, 30, 45, 60 },
        },
    },
    [50] = {
        {
            spell_id = 4037,
            name = "Engineering",
            icon = "trade_engineering",
            source = {
                type = "Trainer",
            },
        },
        {
            spell_id = 7430,
            name = "Arclight Spanner",
            icon = "inv_misc_wrench_01",
            source = {
                type = "Trainer",
                cost = 150,
            },
            product = { item_id = 6219, qty = 1 },
            materials = {
                { item_id = 2840, qty = 6 },
            },
            levels = { 50, 70, 80, 90 },
        },
        {
            spell_id = 3925,
            name = "Rough Boomstick",
            icon = "inv_weapon_rifle_03",
            source = {
                type = "Trainer",
                cost = 150,
            },
            product = { item_id = 4362, qty = 1 },
            materials = {
                { item_id = 4361, qty = 1 },
                { item_id = 4359, qty = 1 },
                { item_id = 4399, qty = 1 },
            },
            levels = { 50, 80, 95, 110 },
        },
        {
            spell_id = 3924,
            name = "Copper Tube",
            icon = "inv_gizmo_pipe_02",
            source = {
                type = "Trainer",
                cost = 150,
            },
            product = { item_id = 4361, qty = 1 },
            materials = {
                { item_id = 2840, qty = 2 },
                { item_id = 2880, qty = 1 },
            },
            levels = { 50, 80, 95, 110 },
        },
    },
    [60] = {
        {
            spell_id = 3977,
            name = "Crude Scope",
            icon = "inv_misc_spyglass_02",
            source = {
                type = "Trainer",
                cost = 200,
            },
            product = { item_id = 4405, qty = 1 },
            materials = {
                { item_id = 4361, qty = 1 },
                { item_id = 774, qty = 1 },
                { item_id = 4359, qty = 1 },
            },
            levels = { 60, 90, 105, 120 },
        },
    },
    [65] = {
        {
            spell_id = 3926,
            name = "Copper Modulator",
            icon = "inv_gizmo_03",
            source = {
                type = "Trainer",
                cost = 225,
            },
            product = { item_id = 4363, qty = 1 },
            materials = {
                { item_id = 4359, qty = 2 },
                { item_id = 2840, qty = 1 },
                { item_id = 2589, qty = 2 },
            },
            levels = { 65, 95, 110, 125 },
        },
    },
    [75] = {
        {
            spell_id = 3929,
            name = "Coarse Blasting Powder",
            icon = "inv_misc_dust_02",
            source = {
                type = "Trainer",
                cost = 250,
            },
            product = { item_id = 4364, qty = 1 },
            materials = {
                { item_id = 2836, qty = 1 },
            },
            levels = { 75, 85, 90, 95 },
        },
        {
            spell_id = 3930,
            name = "Crafted Heavy Shot",
            icon = "inv_ammo_bullet_02",
            source = {
                type = "Trainer",
                cost = 250,
            },
            product = { item_id = 8068, qty = 200 },
            materials = {
                { item_id = 4364, qty = 1 },
                { item_id = 2840, qty = 1 },
            },
            levels = { 75, 85, 90, 95 },
        },
        {
            spell_id = 3931,
            name = "Coarse Dynamite",
            icon = "inv_misc_bomb_06",
            source = {
                type = "Trainer",
                cost = 250,
            },
            product = { item_id = 4365, qty = 1 },
            materials = {
                { item_id = 4364, qty = 3 },
                { item_id = 2589, qty = 1 },
            },
            levels = { 75, 90, 97, 105 },
        },
        {
            spell_id = 3928,
            name = "Mechanical Squirrel",
            icon = "inv_crate_01",
            source = {
                type = "Item",
                recipe_item_ids = { 4408 },
            },
            product = { item_id = 4401, qty = 1 },
            materials = {
                { item_id = 4363, qty = 1 },
                { item_id = 4359, qty = 1 },
                { item_id = 2840, qty = 1 },
                { item_id = 774, qty = 2 },
            },
            levels = { 75, 105, 120, 135 },
        },
    },
    [85] = {
        {
            spell_id = 3932,
            name = "Target Dummy",
            icon = "inv_crate_06",
            source = {
                type = "Trainer",
                cost = 300,
            },
            product = { item_id = 4366, qty = 1 },
            materials = {
                { item_id = 4363, qty = 1 },
                { item_id = 4359, qty = 2 },
                { item_id = 2841, qty = 1 },
                { item_id = 2592, qty = 1 },
            },
            levels = { 85, 115, 130, 145 },
        },
    },
    [90] = {
        {
            spell_id = 3973,
            name = "Silver Contact",
            icon = "inv_ingot_04",
            source = {
                type = "Trainer",
                cost = 300,
            },
            product = { item_id = 4404, qty = 5 },
            materials = {
                { item_id = 2842, qty = 1 },
            },
            levels = { 90, 110, 125, 140 },
        },
    },
    [100] = {
        {
            spell_id = 8339,
            name = "EZ-Thro Dynamite",
            icon = "inv_misc_bomb_06",
            source = {
                type = "Item",
                recipe_item_ids = { 6716 },
            },
            product = { item_id = 6714, qty = 1 },
            materials = {
                { item_id = 4364, qty = 4 },
                { item_id = 2592, qty = 1 },
            },
            levels = { 100, 115, 122, 130 },
        },
        {
            spell_id = 8334,
            name = "Practice Lock",
            icon = "inv_box_01",
            source = {
                type = "Trainer",
                cost = 300,
            },
            product = { item_id = 6712, qty = 1 },
            materials = {
                { item_id = 2841, qty = 1 },
                { item_id = 4359, qty = 2 },
                { item_id = 2880, qty = 1 },
            },
            levels = { 100, 115, 122, 130 },
        },
        {
            spell_id = 3934,
            name = "Flying Tiger Goggles",
            icon = "inv_helmet_47",
            source = {
                type = "Trainer",
                cost = 400,
            },
            product = { item_id = 4368, qty = 1 },
            materials = {
                { item_id = 2318, qty = 6 },
                { item_id = 818, qty = 2 },
            },
            levels = { 100, 130, 145, 160 },
        },
        {
            spell_id = 3933,
            name = "Small Seaforium Charge",
            icon = "inv_misc_urn_01",
            source = {
                type = "Item",
                recipe_item_ids = { 4409 },
            },
            product = { item_id = 4367, qty = 1 },
            materials = {
                { item_id = 4364, qty = 2 },
                { item_id = 4363, qty = 1 },
                { item_id = 2318, qty = 1 },
                { item_id = 159, qty = 1 },
            },
            levels = { 100, 130, 145, 160 },
        },
    },
    [105] = {
        {
            spell_id = 3938,
            name = "Bronze Tube",
            icon = "inv_gizmo_pipe_01",
            source = {
                type = "Trainer",
                cost = 450,
            },
            product = { item_id = 4371, qty = 1 },
            materials = {
                { item_id = 2841, qty = 2 },
                { item_id = 2880, qty = 1 },
            },
            levels = { 105, 105, 130, 155 },
        },
        {
            spell_id = 3937,
            name = "Large Copper Bomb",
            icon = "inv_misc_bomb_01",
            source = {
                type = "Trainer",
                cost = 450,
            },
            product = { item_id = 4370, qty = 2 },
            materials = {
                { item_id = 2840, qty = 3 },
                { item_id = 4364, qty = 4 },
                { item_id = 4404, qty = 1 },
            },
            levels = { 105, 105, 130, 155 },
        },
        {
            spell_id = 3936,
            name = "Deadly Blunderbuss",
            icon = "inv_weapon_rifle_07",
            source = {
                type = "Trainer",
                cost = 420,
            },
            product = { item_id = 4369, qty = 1 },
            materials = {
                { item_id = 4361, qty = 2 },
                { item_id = 4359, qty = 4 },
                { item_id = 4399, qty = 1 },
                { item_id = 2319, qty = 2 },
            },
            levels = { 105, 130, 142, 155 },
        },
    },
    [110] = {
        {
            spell_id = 3978,
            name = "Standard Scope",
            icon = "inv_misc_spyglass_02",
            source = {
                type = "Trainer",
                cost = 475,
            },
            product = { item_id = 4406, qty = 1 },
            materials = {
                { item_id = 4371, qty = 1 },
                { item_id = 1206, qty = 1 },
            },
            levels = { 110, 135, 147, 160 },
        },
    },
    [120] = {
        {
            spell_id = 3941,
            name = "Small Bronze Bomb",
            icon = "inv_misc_bomb_09",
            source = {
                type = "Trainer",
                cost = 500,
            },
            product = { item_id = 4374, qty = 1 },
            materials = {
                { item_id = 4364, qty = 4 },
                { item_id = 2841, qty = 2 },
                { item_id = 4404, qty = 1 },
                { item_id = 2592, qty = 1 },
            },
            levels = { 120, 120, 145, 170 },
        },
        {
            spell_id = 3939,
            name = "Lovingly Crafted Boomstick",
            icon = "inv_weapon_rifle_07",
            source = {
                type = "Item",
                recipe_item_ids = { 13309 },
            },
            product = { item_id = 4372, qty = 1 },
            materials = {
                { item_id = 4371, qty = 2 },
                { item_id = 4359, qty = 2 },
                { item_id = 4400, qty = 1 },
                { item_id = 1206, qty = 3 },
            },
            levels = { 120, 145, 157, 170 },
        },
        {
            spell_id = 3940,
            name = "Shadow Goggles",
            icon = "inv_helmet_47",
            source = {
                type = "Item",
                recipe_item_ids = { 4410 },
            },
            product = { item_id = 4373, qty = 1 },
            materials = {
                { item_id = 2319, qty = 4 },
                { item_id = 1210, qty = 2 },
            },
            levels = { 120, 145, 157, 170 },
        },
    },
    [125] = {
        {
            spell_id = 4038,
            name = "Engineering",
            icon = "trade_engineering",
            source = {
                type = "Trainer",
            },
        },
        {
            spell_id = 3947,
            name = "Crafted Solid Shot",
            icon = "inv_ammo_bullet_02",
            source = {
                type = "Trainer",
                cost = 300,
            },
            product = { item_id = 8069, qty = 200 },
            materials = {
                { item_id = 4377, qty = 1 },
                { item_id = 2841, qty = 1 },
            },
            levels = { 125, 125, 135, 145 },
        },
        {
            spell_id = 3945,
            name = "Heavy Blasting Powder",
            icon = "classic_inv_misc_dust_06",
            source = {
                type = "Trainer",
                cost = 500,
            },
            product = { item_id = 4377, qty = 1 },
            materials = {
                { item_id = 2838, qty = 1 },
            },
            levels = { 125, 125, 135, 145 },
        },
        {
            spell_id = 3946,
            name = "Heavy Dynamite",
            icon = "inv_misc_bomb_06",
            source = {
                type = "Trainer",
                cost = 500,
            },
            product = { item_id = 4378, qty = 1 },
            materials = {
                { item_id = 4377, qty = 2 },
                { item_id = 2592, qty = 1 },
            },
            levels = { 125, 125, 135, 145 },
        },
        {
            spell_id = 26416,
            name = "Small Blue Rocket",
            icon = "inv_misc_missilesmall_blue",
            source = {
                type = "Item",
                recipe_item_ids = { 21724 },
            },
            product = { item_id = 21558, qty = 3 },
            materials = {
                { item_id = 4364, qty = 1 },
                { item_id = 2319, qty = 1 },
            },
            levels = { 125, 125, 137, 150 },
        },
        {
            spell_id = 26417,
            name = "Small Green Rocket",
            icon = "inv_misc_missilesmall_green",
            source = {
                type = "Item",
                recipe_item_ids = { 21725 },
            },
            product = { item_id = 21559, qty = 3 },
            materials = {
                { item_id = 4364, qty = 1 },
                { item_id = 2319, qty = 1 },
            },
            levels = { 125, 125, 137, 150 },
        },
        {
            spell_id = 26418,
            name = "Small Red Rocket",
            icon = "inv_misc_missilesmall_red",
            source = {
                type = "Item",
                recipe_item_ids = { 21726 },
            },
            product = { item_id = 21557, qty = 3 },
            materials = {
                { item_id = 4364, qty = 1 },
                { item_id = 2319, qty = 1 },
            },
            levels = { 125, 125, 137, 150 },
        },
        {
            spell_id = 3944,
            name = "Flame Deflector",
            icon = "inv_gizmo_01",
            source = {
                type = "Item",
                recipe_item_ids = { 4411 },
            },
            product = { item_id = 4376, qty = 1 },
            materials = {
                { item_id = 4375, qty = 1 },
                { item_id = 4402, qty = 1 },
            },
            levels = { 125, 125, 150, 175 },
        },
        {
            spell_id = 3942,
            name = "Whirring Bronze Gizmo",
            icon = "inv_gizmo_02",
            source = {
                type = "Trainer",
                cost = 500,
            },
            product = { item_id = 4375, qty = 1 },
            materials = {
                { item_id = 2841, qty = 2 },
                { item_id = 2592, qty = 1 },
            },
            levels = { 125, 125, 150, 175 },
        },
        {
            spell_id = 9269,
            name = "Gnomish Universal Remote",
            icon = "inv_misc_pocketwatch_01",
            source = {
                type = "Item",
                recipe_item_ids = { 7560 },
            },
            product = { item_id = 7506, qty = 1 },
            materials = {
                { item_id = 2841, qty = 6 },
                { item_id = 4375, qty = 1 },
                { item_id = 814, qty = 2 },
                { item_id = 818, qty = 1 },
                { item_id = 774, qty = 1 },
            },
            levels = { 125, 150, 162, 175 },
        },
    },
    [130] = {
        {
            spell_id = 3949,
            name = "Silver-plated Shotgun",
            icon = "inv_weapon_rifle_07",
            source = {
                type = "Trainer",
                cost = 550,
            },
            product = { item_id = 4379, qty = 1 },
            materials = {
                { item_id = 4371, qty = 2 },
                { item_id = 4375, qty = 2 },
                { item_id = 4400, qty = 1 },
                { item_id = 2842, qty = 3 },
            },
            levels = { 130, 155, 167, 180 },
        },
    },
    [135] = {
        {
            spell_id = 6458,
            name = "Ornate Spyglass",
            icon = "inv_misc_spyglass_01",
            source = {
                type = "Trainer",
                cost = 400,
            },
            product = { item_id = 5507, qty = 1 },
            materials = {
                { item_id = 4371, qty = 2 },
                { item_id = 4375, qty = 2 },
                { item_id = 4363, qty = 1 },
                { item_id = 1206, qty = 1 },
            },
            levels = { 135, 160, 172, 185 },
        },
    },
    [140] = {
        {
            spell_id = 3950,
            name = "Big Bronze Bomb",
            icon = "inv_misc_bomb_05",
            source = {
                type = "Trainer",
                cost = 600,
            },
            product = { item_id = 4380, qty = 2 },
            materials = {
                { item_id = 4377, qty = 2 },
                { item_id = 2841, qty = 3 },
                { item_id = 4404, qty = 1 },
            },
            levels = { 140, 140, 165, 190 },
        },
        {
            spell_id = 3952,
            name = "Minor Recombobulator",
            icon = "inv_gizmo_07",
            source = {
                type = "Item",
                recipe_item_ids = { 14639 },
            },
            product = { item_id = 4381, qty = 1 },
            materials = {
                { item_id = 4371, qty = 1 },
                { item_id = 4375, qty = 2 },
                { item_id = 2319, qty = 2 },
                { item_id = 1206, qty = 1 },
            },
            levels = { 140, 165, 177, 190 },
        },
    },
    [145] = {
        {
            spell_id = 3953,
            name = "Bronze Framework",
            icon = "inv_gizmo_bronzeframework_01",
            source = {
                type = "Trainer",
                cost = 600,
            },
            product = { item_id = 4382, qty = 1 },
            materials = {
                { item_id = 2841, qty = 2 },
                { item_id = 2319, qty = 1 },
                { item_id = 2592, qty = 1 },
            },
            levels = { 145, 145, 170, 195 },
        },
        {
            spell_id = 3954,
            name = "Moonsight Rifle",
            icon = "inv_weapon_rifle_06",
            source = {
                type = "Item",
                recipe_item_ids = { 4412 },
            },
            product = { item_id = 4383, qty = 1 },
            materials = {
                { item_id = 4371, qty = 3 },
                { item_id = 4375, qty = 3 },
                { item_id = 4400, qty = 1 },
                { item_id = 1705, qty = 2 },
            },
            levels = { 145, 170, 182, 195 },
        },
    },
    [150] = {
        {
            spell_id = 9271,
            name = "Aquadynamic Fish Attractor",
            icon = "inv_misc_food_26",
            source = {
                type = "Trainer",
                cost = 500,
            },
            product = { item_id = 6533, qty = 3 },
            materials = {
                { item_id = 2841, qty = 2 },
                { item_id = 6530, qty = 1 },
                { item_id = 4364, qty = 1 },
            },
            levels = { 150, 150, 160, 170 },
        },
        {
            spell_id = 23067,
            name = "Blue Firework",
            icon = "spell_ice_magicdamage",
            source = {
                type = "Item",
                recipe_item_ids = { 18649 },
            },
            product = { item_id = 9312, qty = 3 },
            materials = {
                { item_id = 4377, qty = 1 },
                { item_id = 4234, qty = 1 },
            },
            levels = { 150, 150, 162, 175 },
        },
        {
            spell_id = 23068,
            name = "Green Firework",
            icon = "spell_nature_abolishmagic",
            source = {
                type = "Item",
                recipe_item_ids = { 18648 },
            },
            product = { item_id = 9313, qty = 3 },
            materials = {
                { item_id = 4377, qty = 1 },
                { item_id = 4234, qty = 1 },
            },
            levels = { 150, 150, 162, 175 },
        },
        {
            spell_id = 23066,
            name = "Red Firework",
            icon = "spell_fire_fireball02",
            source = {
                type = "Item",
                recipe_item_ids = { 18647 },
            },
            product = { item_id = 9318, qty = 3 },
            materials = {
                { item_id = 4377, qty = 1 },
                { item_id = 4234, qty = 1 },
            },
            levels = { 150, 150, 162, 175 },
        },
        {
            spell_id = 12584,
            name = "Gold Power Core",
            icon = "inv_battery_02",
            source = {
                type = "Trainer",
                cost = 1000,
            },
            product = { item_id = 10558, qty = 3 },
            materials = {
                { item_id = 3577, qty = 1 },
            },
            levels = { 150, 150, 170, 190 },
        },
        {
            spell_id = 3956,
            name = "Green Tinted Goggles",
            icon = "inv_helmet_47",
            source = {
                type = "Trainer",
                cost = 750,
            },
            product = { item_id = 4385, qty = 1 },
            materials = {
                { item_id = 2319, qty = 4 },
                { item_id = 1206, qty = 2 },
                { item_id = 4368, qty = 1 },
            },
            levels = { 150, 175, 187, 200 },
        },
        {
            spell_id = 3955,
            name = "Explosive Sheep",
            icon = "spell_nature_polymorph",
            source = {
                type = "Trainer",
                cost = 750,
            },
            product = { item_id = 4384, qty = 1 },
            materials = {
                { item_id = 4382, qty = 1 },
                { item_id = 4375, qty = 1 },
                { item_id = 4377, qty = 2 },
                { item_id = 2592, qty = 2 },
            },
            levels = { 150, 175, 187, 200 },
        },
    },
    [155] = {
        {
            spell_id = 3957,
            name = "Ice Deflector",
            icon = "inv_gizmo_01",
            source = {
                type = "Item",
                recipe_item_ids = { 13308 },
            },
            product = { item_id = 4386, qty = 1 },
            materials = {
                { item_id = 4375, qty = 1 },
                { item_id = 3829, qty = 1 },
            },
            levels = { 155, 175, 185, 195 },
        },
    },
    [160] = {
        {
            spell_id = 3958,
            name = "Iron Strut",
            icon = "inv_spear_05",
            source = {
                type = "Trainer",
                cost = 800,
            },
            product = { item_id = 4387, qty = 1 },
            materials = {
                { item_id = 3575, qty = 2 },
            },
            levels = { 160, 160, 170, 180 },
        },
        {
            spell_id = 3959,
            name = "Discombobulator Ray",
            icon = "inv_misc_spyglass_02",
            source = {
                type = "Item",
                recipe_item_ids = { 4413 },
            },
            product = { item_id = 4388, qty = 1 },
            materials = {
                { item_id = 4375, qty = 3 },
                { item_id = 4306, qty = 2 },
                { item_id = 1529, qty = 1 },
                { item_id = 4371, qty = 1 },
            },
            levels = { 160, 180, 190, 200 },
        },
    },
    [165] = {
        {
            spell_id = 9273,
            name = "Goblin Jumper Cables",
            icon = "inv_misc_enggizmos_10",
            source = {
                type = "Item",
                recipe_item_ids = { 7561 },
            },
            product = { item_id = 7148, qty = 1 },
            materials = {
                { item_id = 3575, qty = 6 },
                { item_id = 4375, qty = 2 },
                { item_id = 814, qty = 2 },
                { item_id = 4306, qty = 2 },
                { item_id = 1210, qty = 2 },
                { item_id = 7191, qty = 1 },
            },
            levels = { 165, 160, 180, 200 },
        },
        {
            spell_id = 3960,
            name = "Portable Bronze Mortar",
            icon = "inv_musket_01",
            source = {
                type = "Item",
                recipe_item_ids = { 4414 },
            },
            product = { item_id = 4403, qty = 1 },
            materials = {
                { item_id = 4371, qty = 4 },
                { item_id = 4387, qty = 1 },
                { item_id = 4377, qty = 4 },
                { item_id = 2319, qty = 4 },
            },
            levels = { 165, 185, 195, 205 },
        },
    },
    [170] = {
        {
            spell_id = 3961,
            name = "Gyrochronatom",
            icon = "inv_misc_pocketwatch_02",
            source = {
                type = "Trainer",
                cost = 900,
            },
            product = { item_id = 4389, qty = 1 },
            materials = {
                { item_id = 3575, qty = 1 },
                { item_id = 10558, qty = 1 },
            },
            levels = { 170, 170, 190, 210 },
        },
    },
    [175] = {
        {
            spell_id = 12585,
            name = "Solid Blasting Powder",
            icon = "inv_misc_powder_black",
            source = {
                type = "Trainer",
                cost = 1000,
            },
            product = { item_id = 10505, qty = 1 },
            materials = {
                { item_id = 7912, qty = 2 },
            },
            levels = { 175, 175, 185, 195 },
        },
        {
            spell_id = 12586,
            name = "Solid Dynamite",
            icon = "inv_misc_bomb_06",
            source = {
                type = "Trainer",
                cost = 1000,
            },
            product = { item_id = 10507, qty = 2 },
            materials = {
                { item_id = 10505, qty = 1 },
                { item_id = 4306, qty = 1 },
            },
            levels = { 175, 175, 185, 195 },
        },
        {
            spell_id = 26420,
            name = "Large Blue Rocket",
            icon = "inv_misc_missilelarge_blue",
            source = {
                type = "Item",
                recipe_item_ids = { 21727 },
            },
            product = { item_id = 21589, qty = 3 },
            materials = {
                { item_id = 4377, qty = 1 },
                { item_id = 4234, qty = 1 },
            },
            levels = { 175, 175, 187, 200 },
        },
        {
            spell_id = 26421,
            name = "Large Green Rocket",
            icon = "inv_misc_missilelarge_green",
            source = {
                type = "Item",
                recipe_item_ids = { 21728 },
            },
            product = { item_id = 21590, qty = 3 },
            materials = {
                { item_id = 4377, qty = 1 },
                { item_id = 4234, qty = 1 },
            },
            levels = { 175, 175, 187, 200 },
        },
        {
            spell_id = 26422,
            name = "Large Red Rocket",
            icon = "inv_misc_missilelarge_red",
            source = {
                type = "Item",
                recipe_item_ids = { 21729 },
            },
            product = { item_id = 21592, qty = 3 },
            materials = {
                { item_id = 4377, qty = 1 },
                { item_id = 4234, qty = 1 },
            },
            levels = { 175, 175, 187, 200 },
        },
        {
            spell_id = 3963,
            name = "Compact Harvest Reaper Kit",
            icon = "inv_helmet_08",
            source = {
                type = "Trainer",
                cost = 1000,
            },
            product = { item_id = 4391, qty = 1 },
            materials = {
                { item_id = 4387, qty = 2 },
                { item_id = 4382, qty = 1 },
                { item_id = 4389, qty = 2 },
                { item_id = 4234, qty = 4 },
            },
            levels = { 175, 175, 195, 215 },
        },
        {
            spell_id = 12590,
            name = "Gyromatic Micro-Adjustor",
            icon = "inv_misc_screwdriver_02",
            source = {
                type = "Trainer",
                cost = 1000,
            },
            product = { item_id = 10498, qty = 1 },
            materials = {
                { item_id = 3859, qty = 4 },
            },
            levels = { 175, 175, 195, 215 },
        },
        {
            spell_id = 3962,
            name = "Iron Grenade",
            icon = "inv_misc_bomb_08",
            source = {
                type = "Trainer",
                cost = 1000,
            },
            product = { item_id = 4390, qty = 2 },
            materials = {
                { item_id = 3575, qty = 1 },
                { item_id = 4377, qty = 1 },
                { item_id = 4306, qty = 1 },
            },
            levels = { 175, 175, 195, 215 },
        },
        {
            spell_id = 12587,
            name = "Bright-Eye Goggles",
            icon = "inv_helmet_47",
            source = {
                type = "Item",
                recipe_item_ids = { 10601 },
            },
            product = { item_id = 10499, qty = 1 },
            materials = {
                { item_id = 4234, qty = 6 },
                { item_id = 3864, qty = 2 },
            },
            levels = { 175, 195, 205, 215 },
        },
    },
    [180] = {
        {
            spell_id = 3979,
            name = "Accurate Scope",
            icon = "inv_misc_spyglass_02",
            source = {
                type = "Item",
                recipe_item_ids = { 13310 },
            },
            product = { item_id = 4407, qty = 1 },
            materials = {
                { item_id = 4371, qty = 1 },
                { item_id = 1529, qty = 1 },
                { item_id = 3864, qty = 1 },
            },
            levels = { 180, 200, 210, 220 },
        },
    },
    [185] = {
        {
            spell_id = 3965,
            name = "Advanced Target Dummy",
            icon = "inv_crate_05",
            source = {
                type = "Trainer",
                cost = 1200,
            },
            product = { item_id = 4392, qty = 1 },
            materials = {
                { item_id = 4387, qty = 1 },
                { item_id = 4382, qty = 1 },
                { item_id = 4389, qty = 1 },
                { item_id = 4234, qty = 4 },
            },
            levels = { 185, 185, 205, 225 },
        },
        {
            spell_id = 8243,
            name = "Flash Bomb",
            icon = "inv_misc_ammo_bullet_01",
            source = {
                type = "Item",
                recipe_item_ids = { 6672 },
            },
            product = { item_id = 4852, qty = 1 },
            materials = {
                { item_id = 4611, qty = 1 },
                { item_id = 4377, qty = 1 },
                { item_id = 4306, qty = 1 },
            },
            levels = { 185, 185, 205, 225 },
        },
        {
            spell_id = 3966,
            name = "Craftsman's Monocle",
            icon = "inv_helmet_44",
            source = {
                type = "Item",
                recipe_item_ids = { 4415 },
            },
            product = { item_id = 4393, qty = 1 },
            materials = {
                { item_id = 4234, qty = 6 },
                { item_id = 3864, qty = 2 },
            },
            levels = { 185, 205, 215, 225 },
        },
    },
    [190] = {
        {
            spell_id = 3967,
            name = "Big Iron Bomb",
            icon = "inv_misc_bomb_01",
            source = {
                type = "Trainer",
                cost = 1400,
            },
            product = { item_id = 4394, qty = 2 },
            materials = {
                { item_id = 3575, qty = 3 },
                { item_id = 4377, qty = 3 },
                { item_id = 4404, qty = 1 },
            },
            levels = { 190, 190, 210, 230 },
        },
        {
            spell_id = 21940,
            name = "SnowMaster 9000",
            icon = "spell_frost_windwalkon",
            source = {
                type = "Item",
                recipe_item_ids = { 17720 },
            },
            product = { item_id = 17716, qty = 1 },
            materials = {
                { item_id = 3860, qty = 8 },
                { item_id = 4389, qty = 4 },
                { item_id = 17202, qty = 4 },
                { item_id = 3829, qty = 1 },
            },
            levels = { 190, 190, 210, 230 },
        },
    },
    [195] = {
        {
            spell_id = 12589,
            name = "Mithril Tube",
            icon = "inv_musket_01",
            source = {
                type = "Trainer",
                cost = 1300,
            },
            product = { item_id = 10559, qty = 1 },
            materials = {
                { item_id = 3860, qty = 3 },
            },
            levels = { 195, 195, 215, 235 },
        },
        {
            spell_id = 3968,
            name = "Goblin Land Mine",
            icon = "inv_shield_08",
            source = {
                type = "Item",
                recipe_item_ids = { 4416 },
            },
            product = { item_id = 4395, qty = 1 },
            materials = {
                { item_id = 4377, qty = 3 },
                { item_id = 3575, qty = 2 },
                { item_id = 4389, qty = 1 },
            },
            levels = { 195, 215, 225, 235 },
        },
    },
    [200] = {
        {
            spell_id = 12656,
            name = "Engineering",
            icon = "trade_engineering",
            source = {
                type = "Trainer",
            },
        },
        {
            spell_id = 23069,
            name = "EZ-Thro Dynamite II",
            icon = "inv_misc_bomb_03",
            source = {
                type = "Item",
                recipe_item_ids = { 18650 },
            },
            product = { item_id = 18588, qty = 1 },
            materials = {
                { item_id = 10505, qty = 1 },
                { item_id = 4338, qty = 2 },
            },
            levels = { 200, 200, 210, 220 },
        },
        {
            spell_id = 3972,
            name = "Large Seaforium Charge",
            icon = "inv_misc_urn_01",
            source = {
                type = "Item",
                recipe_item_ids = { 4417 },
            },
            product = { item_id = 4398, qty = 1 },
            materials = {
                { item_id = 10505, qty = 2 },
                { item_id = 4234, qty = 2 },
                { item_id = 159, qty = 1 },
            },
            levels = { 200, 200, 220, 240 },
        },
        {
            spell_id = 15255,
            name = "Mechanical Repair Kit",
            icon = "inv_gizmo_03",
            source = {
                type = "Trainer",
                cost = 1500,
            },
            product = { item_id = 11590, qty = 1 },
            materials = {
                { item_id = 3860, qty = 1 },
                { item_id = 4338, qty = 1 },
                { item_id = 10505, qty = 1 },
            },
            levels = { 200, 200, 220, 240 },
        },
        {
            spell_id = 12591,
            name = "Unstable Trigger",
            icon = "inv_battery_01",
            source = {
                type = "Trainer",
                cost = 1500,
            },
            product = { item_id = 10560, qty = 1 },
            materials = {
                { item_id = 3860, qty = 1 },
                { item_id = 4338, qty = 1 },
                { item_id = 10505, qty = 1 },
            },
            levels = { 200, 200, 220, 240 },
        },
        {
            spell_id = 3971,
            name = "Gnomish Cloaking Device",
            icon = "inv_gizmo_01",
            source = {
                type = "Item",
                recipe_item_ids = { 7742 },
            },
            product = { item_id = 4397, qty = 1 },
            materials = {
                { item_id = 4389, qty = 4 },
                { item_id = 1529, qty = 2 },
                { item_id = 1705, qty = 2 },
                { item_id = 3864, qty = 2 },
                { item_id = 7191, qty = 1 },
            },
            levels = { 200, 220, 230, 240 },
        },
        {
            spell_id = 3969,
            name = "Mechanical Dragonling",
            icon = "inv_misc_head_dragon_01",
            source = {
                type = "Item",
                recipe_item_ids = { 13311 },
            },
            product = { item_id = 4396, qty = 1 },
            materials = {
                { item_id = 4382, qty = 1 },
                { item_id = 4387, qty = 4 },
                { item_id = 4389, qty = 4 },
                { item_id = 3864, qty = 2 },
                { item_id = 7191, qty = 1 },
            },
            levels = { 200, 220, 230, 240 },
        },
    },
    [205] = {
        {
            spell_id = 13240,
            name = "The Mortar: Reloaded",
            icon = "inv_musket_01",
            source = {
                type = "Trainer",
            },
            product = { item_id = 10577, qty = 1 },
            materials = {
                { item_id = 10577, qty = 1 },
                { item_id = 3860, qty = 1 },
                { item_id = 10505, qty = 3 },
            },
            levels = { 205, 225, 235, 245 },
        },
        {
            spell_id = 12715,
            name = "Goblin Rocket Fuel Recipe",
            icon = "inv_scroll_03",
            source = {
                type = "Trainer",
                cost = 1000,
            },
            product = { item_id = 10644, qty = 1 },
            materials = {
                { item_id = 10648, qty = 1 },
                { item_id = 10647, qty = 1 },
            },
            levels = { 205, 205, 205, 205 },
        },
        {
            spell_id = 12895,
            name = "Inlaid Mithril Cylinder Plans",
            icon = "inv_scroll_05",
            source = {
                type = "Trainer",
                cost = 1500,
            },
            product = { item_id = 10713, qty = 1 },
            materials = {
                { item_id = 10648, qty = 1 },
                { item_id = 10647, qty = 1 },
            },
            levels = { 205, 205, 205, 205 },
        },
        {
            spell_id = 15633,
            name = "Lil' Smoky",
            icon = "inv_misc_idol_02",
            source = {
                type = "Item",
                recipe_item_ids = { 11827 },
            },
            product = { item_id = 11826, qty = 1 },
            materials = {
                { item_id = 7075, qty = 1 },
                { item_id = 4389, qty = 2 },
                { item_id = 7191, qty = 1 },
                { item_id = 3860, qty = 2 },
                { item_id = 6037, qty = 1 },
            },
            levels = { 205, 205, 205, 205 },
        },
        {
            spell_id = 15628,
            name = "Pet Bombling",
            icon = "inv_misc_bomb_04",
            source = {
                type = "Item",
                recipe_item_ids = { 11828 },
            },
            product = { item_id = 11825, qty = 1 },
            materials = {
                { item_id = 4394, qty = 1 },
                { item_id = 7077, qty = 1 },
                { item_id = 7191, qty = 1 },
                { item_id = 3860, qty = 6 },
            },
            levels = { 205, 205, 205, 205 },
        },
        {
            spell_id = 12760,
            name = "Goblin Sapper Charge",
            icon = "spell_fire_selfdestruct",
            source = {
                type = "Trainer",
                cost = 1500,
            },
            product = { item_id = 10646, qty = 1 },
            materials = {
                { item_id = 4338, qty = 1 },
                { item_id = 10505, qty = 3 },
                { item_id = 10560, qty = 1 },
            },
            levels = { 205, 205, 225, 245 },
        },
        {
            spell_id = 12594,
            name = "Fire Goggles",
            icon = "inv_helmet_47",
            source = {
                type = "Trainer",
                cost = 1600,
            },
            product = { item_id = 10500, qty = 1 },
            materials = {
                { item_id = 4385, qty = 1 },
                { item_id = 3864, qty = 2 },
                { item_id = 7068, qty = 2 },
                { item_id = 4234, qty = 4 },
            },
            levels = { 205, 225, 235, 245 },
        },
        {
            spell_id = 12718,
            name = "Goblin Construction Helmet",
            icon = "inv_helmet_60",
            source = {
                type = "Trainer",
                cost = 1500,
            },
            product = { item_id = 10543, qty = 1 },
            materials = {
                { item_id = 3860, qty = 8 },
                { item_id = 3864, qty = 1 },
                { item_id = 7068, qty = 4 },
            },
            levels = { 205, 225, 235, 245 },
        },
        {
            spell_id = 12717,
            name = "Goblin Mining Helmet",
            icon = "inv_helmet_25",
            source = {
                type = "Trainer",
                cost = 1500,
            },
            product = { item_id = 10542, qty = 1 },
            materials = {
                { item_id = 3860, qty = 8 },
                { item_id = 3864, qty = 1 },
                { item_id = 7067, qty = 4 },
            },
            levels = { 205, 225, 235, 245 },
        },
        {
            spell_id = 12595,
            name = "Mithril Blunderbuss",
            icon = "inv_weapon_rifle_07",
            source = {
                type = "Trainer",
                cost = 1600,
            },
            product = { item_id = 10508, qty = 1 },
            materials = {
                { item_id = 10559, qty = 1 },
                { item_id = 10560, qty = 1 },
                { item_id = 4400, qty = 1 },
                { item_id = 3860, qty = 4 },
                { item_id = 7068, qty = 2 },
            },
            levels = { 205, 225, 235, 245 },
        },
        {
            spell_id = 12899,
            name = "Gnomish Shrink Ray",
            icon = "inv_gizmo_09",
            source = {
                type = "Trainer",
                cost = 1500,
            },
            product = { item_id = 10716, qty = 1 },
            materials = {
                { item_id = 10559, qty = 1 },
                { item_id = 10560, qty = 1 },
                { item_id = 3860, qty = 4 },
                { item_id = 8151, qty = 4 },
                { item_id = 1529, qty = 2 },
            },
            levels = { 205, 225, 235, 245 },
        },
    },
    [210] = {
        {
            spell_id = 12596,
            name = "Hi-Impact Mithril Slugs",
            icon = "inv_ammo_bullet_01",
            source = {
                type = "Trainer",
                cost = 1700,
            },
            product = { item_id = 10512, qty = 200 },
            materials = {
                { item_id = 3860, qty = 1 },
                { item_id = 10505, qty = 1 },
            },
            levels = { 210, 210, 230, 250 },
        },
        {
            spell_id = 12897,
            name = "Gnomish Goggles",
            icon = "inv_helmet_47",
            source = {
                type = "Trainer",
                cost = 1500,
            },
            product = { item_id = 10545, qty = 1 },
            materials = {
                { item_id = 10500, qty = 1 },
                { item_id = 10559, qty = 1 },
                { item_id = 10558, qty = 2 },
                { item_id = 8151, qty = 2 },
                { item_id = 4234, qty = 2 },
            },
            levels = { 210, 230, 240, 250 },
        },
        {
            spell_id = 12597,
            name = "Deadly Scope",
            icon = "inv_misc_spyglass_02",
            source = {
                type = "Item",
                recipe_item_ids = { 10602 },
            },
            product = { item_id = 10546, qty = 1 },
            materials = {
                { item_id = 10559, qty = 1 },
                { item_id = 7909, qty = 2 },
                { item_id = 4304, qty = 2 },
            },
            levels = { 210, 230, 240, 250 },
        },
        {
            spell_id = 12902,
            name = "Gnomish Net-o-Matic Projector",
            icon = "inv_misc_net_01",
            source = {
                type = "Trainer",
                cost = 1800,
            },
            product = { item_id = 10720, qty = 1 },
            materials = {
                { item_id = 10559, qty = 1 },
                { item_id = 10285, qty = 2 },
                { item_id = 4337, qty = 4 },
                { item_id = 10505, qty = 2 },
                { item_id = 3860, qty = 4 },
            },
            levels = { 210, 230, 240, 250 },
        },
    },
    [215] = {
        {
            spell_id = 12599,
            name = "Mithril Casing",
            icon = "inv_gizmo_mithrilcasing_01",
            source = {
                type = "Trainer",
                cost = 1800,
            },
            product = { item_id = 10561, qty = 1 },
            materials = {
                { item_id = 3860, qty = 3 },
            },
            levels = { 215, 215, 235, 255 },
        },
        {
            spell_id = 12603,
            name = "Mithril Frag Bomb",
            icon = "inv_misc_bomb_02",
            source = {
                type = "Trainer",
                cost = 1800,
            },
            product = { item_id = 10514, qty = 3 },
            materials = {
                { item_id = 10561, qty = 1 },
                { item_id = 10560, qty = 1 },
                { item_id = 10505, qty = 1 },
            },
            levels = { 215, 215, 235, 255 },
        },
        {
            spell_id = 12903,
            name = "Gnomish Harm Prevention Belt",
            icon = "inv_belt_06",
            source = {
                type = "Trainer",
                cost = 2000,
            },
            product = { item_id = 10721, qty = 1 },
            materials = {
                { item_id = 7387, qty = 1 },
                { item_id = 3860, qty = 4 },
                { item_id = 6037, qty = 2 },
                { item_id = 10560, qty = 1 },
                { item_id = 7909, qty = 2 },
            },
            levels = { 215, 235, 245, 255 },
        },
    },
    [220] = {
        {
            spell_id = 12607,
            name = "Catseye Ultra Goggles",
            icon = "inv_helmet_47",
            source = {
                type = "Item",
                recipe_item_ids = { 10603 },
            },
            product = { item_id = 10501, qty = 1 },
            materials = {
                { item_id = 4304, qty = 4 },
                { item_id = 7909, qty = 2 },
                { item_id = 10592, qty = 1 },
            },
            levels = { 220, 240, 250, 260 },
        },
        {
            spell_id = 12614,
            name = "Mithril Heavy-bore Rifle",
            icon = "inv_weapon_rifle_07",
            source = {
                type = "Item",
                recipe_item_ids = { 10604 },
            },
            product = { item_id = 10510, qty = 1 },
            materials = {
                { item_id = 10559, qty = 2 },
                { item_id = 10560, qty = 1 },
                { item_id = 4400, qty = 1 },
                { item_id = 3860, qty = 6 },
                { item_id = 3864, qty = 2 },
            },
            levels = { 220, 240, 250, 260 },
        },
    },
    [225] = {
        {
            spell_id = 26423,
            name = "Blue Rocket Cluster",
            icon = "inv_misc_missilesmallcluster_blue",
            source = {
                type = "Item",
                recipe_item_ids = { 21730 },
            },
            product = { item_id = 21571, qty = 3 },
            materials = {
                { item_id = 10505, qty = 1 },
                { item_id = 4304, qty = 1 },
            },
            levels = { 225, 225, 237, 250 },
        },
        {
            spell_id = 26424,
            name = "Green Rocket Cluster",
            icon = "inv_misc_missilesmallcluster_green",
            source = {
                type = "Item",
                recipe_item_ids = { 21731 },
            },
            product = { item_id = 21574, qty = 3 },
            materials = {
                { item_id = 10505, qty = 1 },
                { item_id = 4304, qty = 1 },
            },
            levels = { 225, 225, 237, 250 },
        },
        {
            spell_id = 26425,
            name = "Red Rocket Cluster",
            icon = "inv_misc_missilesmallcluster_red",
            source = {
                type = "Item",
                recipe_item_ids = { 21732 },
            },
            product = { item_id = 21576, qty = 3 },
            materials = {
                { item_id = 10505, qty = 1 },
                { item_id = 4304, qty = 1 },
            },
            levels = { 225, 225, 237, 250 },
        },
        {
            spell_id = 12905,
            name = "Gnomish Rocket Boots",
            icon = "inv_boots_02",
            source = {
                type = "Trainer",
                cost = 2200,
            },
            product = { item_id = 10724, qty = 1 },
            materials = {
                { item_id = 10026, qty = 1 },
                { item_id = 10559, qty = 2 },
                { item_id = 4234, qty = 4 },
                { item_id = 10505, qty = 8 },
                { item_id = 4389, qty = 4 },
            },
            levels = { 225, 245, 255, 265 },
        },
        {
            spell_id = 8895,
            name = "Goblin Rocket Boots",
            icon = "inv_gizmo_rocketboot_01",
            source = {
                type = "Trainer",
                cost = 2200,
            },
            product = { item_id = 7189, qty = 1 },
            materials = {
                { item_id = 10026, qty = 1 },
                { item_id = 10559, qty = 2 },
                { item_id = 4234, qty = 4 },
                { item_id = 9061, qty = 2 },
                { item_id = 10560, qty = 1 },
            },
            levels = { 225, 245, 255, 265 },
        },
        {
            spell_id = 12616,
            name = "Parachute Cloak",
            icon = "inv_misc_cape_11",
            source = {
                type = "Item",
                recipe_item_ids = { 10606 },
            },
            product = { item_id = 10518, qty = 1 },
            materials = {
                { item_id = 4339, qty = 4 },
                { item_id = 10285, qty = 2 },
                { item_id = 10560, qty = 1 },
                { item_id = 10505, qty = 4 },
            },
            levels = { 225, 245, 255, 265 },
        },
        {
            spell_id = 12615,
            name = "Spellpower Goggles Xtreme",
            icon = "inv_helmet_47",
            source = {
                type = "Item",
                recipe_item_ids = { 10605 },
            },
            product = { item_id = 10502, qty = 1 },
            materials = {
                { item_id = 4304, qty = 4 },
                { item_id = 7910, qty = 2 },
            },
            levels = { 225, 245, 255, 265 },
        },
        {
            spell_id = 26442,
            name = "Firework Launcher",
            icon = "inv_musket_04",
            source = {
                type = "Item",
                recipe_item_ids = { 21738 },
            },
            product = { item_id = 21569, qty = 1 },
            materials = {
                { item_id = 9060, qty = 1 },
                { item_id = 9061, qty = 1 },
                { item_id = 10560, qty = 1 },
                { item_id = 10561, qty = 1 },
            },
            levels = { 225, 245, 255, 265 },
        },
        {
            spell_id = 12716,
            name = "Goblin Mortar",
            icon = "inv_musket_01",
            source = {
                type = "Trainer",
                cost = 1500,
            },
            product = { item_id = 10577, qty = 1 },
            materials = {
                { item_id = 10559, qty = 2 },
                { item_id = 3860, qty = 4 },
                { item_id = 10505, qty = 5 },
                { item_id = 10558, qty = 1 },
                { item_id = 7068, qty = 1 },
            },
            levels = { 205, 225, 235, 245 },
        },
    },
    [230] = {
        {
            spell_id = 12755,
            name = "Goblin Bomb Dispenser",
            icon = "inv_gizmo_06",
            source = {
                type = "Trainer",
                cost = 2400,
            },
            product = { item_id = 10587, qty = 1 },
            materials = {
                { item_id = 10561, qty = 2 },
                { item_id = 10505, qty = 4 },
                { item_id = 6037, qty = 6 },
                { item_id = 10560, qty = 1 },
                { item_id = 4407, qty = 2 },
            },
            levels = { 230, 230, 250, 270 },
        },
        {
            spell_id = 12617,
            name = "Deepdive Helmet",
            icon = "inv_helmet_49",
            source = {
                type = "Item",
                recipe_item_ids = { 10607 },
            },
            product = { item_id = 10506, qty = 1 },
            materials = {
                { item_id = 3860, qty = 8 },
                { item_id = 10561, qty = 1 },
                { item_id = 6037, qty = 1 },
                { item_id = 818, qty = 4 },
                { item_id = 774, qty = 4 },
            },
            levels = { 230, 250, 260, 270 },
        },
        {
            spell_id = 12618,
            name = "Rose Colored Goggles",
            icon = "inv_helmet_47",
            source = {
                type = "Trainer",
                cost = 2200,
            },
            product = { item_id = 10503, qty = 1 },
            materials = {
                { item_id = 4304, qty = 6 },
                { item_id = 7910, qty = 2 },
            },
            levels = { 230, 250, 260, 270 },
        },
        {
            spell_id = 12906,
            name = "Gnomish Battle Chicken",
            icon = "spell_magic_polymorphchicken",
            source = {
                type = "Trainer",
                cost = 2400,
            },
            product = { item_id = 10725, qty = 1 },
            materials = {
                { item_id = 10561, qty = 1 },
                { item_id = 6037, qty = 6 },
                { item_id = 3860, qty = 6 },
                { item_id = 9060, qty = 2 },
                { item_id = 10558, qty = 1 },
                { item_id = 1529, qty = 2 },
            },
            levels = { 230, 250, 260, 270 },
        },
    },
    [235] = {
        {
            spell_id = 12619,
            name = "Hi-Explosive Bomb",
            icon = "inv_misc_bomb_07",
            source = {
                type = "Trainer",
                cost = 2400,
            },
            product = { item_id = 10562, qty = 4 },
            materials = {
                { item_id = 10561, qty = 2 },
                { item_id = 10560, qty = 1 },
                { item_id = 10505, qty = 2 },
            },
            levels = { 235, 235, 255, 275 },
        },
        {
            spell_id = 12754,
            name = "The Big One",
            icon = "inv_misc_bomb_04",
            source = {
                type = "Trainer",
                cost = 2600,
            },
            product = { item_id = 10586, qty = 2 },
            materials = {
                { item_id = 10561, qty = 1 },
                { item_id = 9061, qty = 1 },
                { item_id = 10507, qty = 6 },
                { item_id = 10560, qty = 1 },
            },
            levels = { 235, 235, 255, 275 },
        },
        {
            spell_id = 12907,
            name = "Gnomish Mind Control Cap",
            icon = "inv_helmet_49",
            source = {
                type = "Trainer",
                cost = 2600,
            },
            product = { item_id = 10726, qty = 1 },
            materials = {
                { item_id = 3860, qty = 10 },
                { item_id = 6037, qty = 4 },
                { item_id = 10558, qty = 1 },
                { item_id = 7910, qty = 2 },
                { item_id = 4338, qty = 4 },
            },
            levels = { 235, 255, 265, 275 },
        },
    },
    [240] = {
        {
            spell_id = 12759,
            name = "Gnomish Death Ray",
            icon = "inv_gizmo_08",
            source = {
                type = "Trainer",
                cost = 2800,
            },
            product = { item_id = 10645, qty = 1 },
            materials = {
                { item_id = 10559, qty = 2 },
                { item_id = 10560, qty = 1 },
                { item_id = 12808, qty = 1 },
                { item_id = 7972, qty = 4 },
                { item_id = 9060, qty = 1 },
            },
            levels = { 240, 260, 270, 280 },
        },
        {
            spell_id = 12908,
            name = "Goblin Dragon Gun",
            icon = "spell_fire_flamebolt",
            source = {
                type = "Trainer",
                cost = 2800,
            },
            product = { item_id = 10727, qty = 1 },
            materials = {
                { item_id = 10559, qty = 2 },
                { item_id = 9061, qty = 4 },
                { item_id = 3860, qty = 6 },
                { item_id = 6037, qty = 6 },
                { item_id = 10560, qty = 1 },
            },
            levels = { 240, 260, 270, 280 },
        },
        {
            spell_id = 12620,
            name = "Sniper Scope",
            icon = "inv_misc_spyglass_02",
            source = {
                type = "Item",
                recipe_item_ids = { 10608 },
            },
            product = { item_id = 10548, qty = 1 },
            materials = {
                { item_id = 10559, qty = 1 },
                { item_id = 7910, qty = 1 },
                { item_id = 6037, qty = 2 },
            },
            levels = { 240, 260, 270, 280 },
        },
    },
    [245] = {
        {
            spell_id = 12621,
            name = "Mithril Gyro-Shot",
            icon = "inv_ammo_bullet_01",
            source = {
                type = "Trainer",
                cost = 2800,
            },
            product = { item_id = 10513, qty = 200 },
            materials = {
                { item_id = 3860, qty = 2 },
                { item_id = 10505, qty = 2 },
            },
            levels = { 245, 245, 265, 285 },
        },
        {
            spell_id = 12622,
            name = "Green Lens",
            icon = "inv_helmet_44",
            source = {
                type = "Trainer",
                cost = 2800,
            },
            product = { item_id = 10504, qty = 1 },
            materials = {
                { item_id = 4304, qty = 8 },
                { item_id = 1529, qty = 3 },
                { item_id = 7909, qty = 3 },
                { item_id = 10286, qty = 2 },
                { item_id = 8153, qty = 2 },
            },
            levels = { 245, 265, 275, 285 },
        },
        {
            spell_id = 12758,
            name = "Goblin Rocket Helmet",
            icon = "inv_helmet_49",
            source = {
                type = "Trainer",
                cost = 3000,
            },
            product = { item_id = 10588, qty = 1 },
            materials = {
                { item_id = 10543, qty = 1 },
                { item_id = 9061, qty = 4 },
                { item_id = 3860, qty = 4 },
                { item_id = 10560, qty = 1 },
            },
            levels = { 245, 265, 275, 285 },
        },
    },
    [250] = {
        {
            spell_id = 19788,
            name = "Dense Blasting Powder",
            icon = "inv_misc_ammo_gunpowder_01",
            source = {
                type = "Trainer",
                cost = 4000,
            },
            product = { item_id = 15992, qty = 1 },
            materials = {
                { item_id = 12365, qty = 2 },
            },
            levels = { 250, 250, 255, 260 },
        },
        {
            spell_id = 23070,
            name = "Dense Dynamite",
            icon = "inv_misc_bomb_06",
            source = {
                type = "Trainer",
                cost = 5000,
            },
            product = { item_id = 18641, qty = 2 },
            materials = {
                { item_id = 15992, qty = 2 },
                { item_id = 14047, qty = 3 },
            },
            levels = { 250, 250, 260, 270 },
        },
        {
            spell_id = 23507,
            name = "Snake Burst Firework",
            icon = "spell_holy_holybolt",
            source = {
                type = "Item",
                recipe_item_ids = { 19027 },
            },
            product = { item_id = 19026, qty = 4 },
            materials = {
                { item_id = 15992, qty = 2 },
                { item_id = 14047, qty = 2 },
                { item_id = 8150, qty = 1 },
            },
            levels = { 250, 250, 260, 270 },
        },
        {
            spell_id = 12624,
            name = "Mithril Mechanical Dragonling",
            icon = "inv_misc_head_dragon_01",
            source = {
                type = "Item",
                recipe_item_ids = { 10609 },
            },
            product = { item_id = 10576, qty = 1 },
            materials = {
                { item_id = 3860, qty = 14 },
                { item_id = 7077, qty = 4 },
                { item_id = 6037, qty = 4 },
                { item_id = 9060, qty = 2 },
                { item_id = 9061, qty = 2 },
                { item_id = 7910, qty = 2 },
            },
            levels = { 250, 270, 280, 290 },
        },
        {
            spell_id = 19567,
            name = "Salt Shaker",
            icon = "inv_egg_05",
            source = {
                type = "Trainer",
                cost = 4000,
            },
            product = { item_id = 15846, qty = 1 },
            materials = {
                { item_id = 10561, qty = 1 },
                { item_id = 12359, qty = 6 },
                { item_id = 10558, qty = 1 },
                { item_id = 10560, qty = 4 },
            },
            levels = { 250, 270, 280, 290 },
        },
        {
            spell_id = 26011,
            name = "Tranquil Mechanical Yeti",
            icon = "ability_hunter_pet_gorilla",
            source = {
                type = "Quest",
                quest_ids = { 8798 },
            },
            product = { item_id = 21277, qty = 1 },
            materials = {
                { item_id = 15407, qty = 1 },
                { item_id = 15994, qty = 4 },
                { item_id = 7079, qty = 2 },
                { item_id = 18631, qty = 2 },
                { item_id = 10558, qty = 1 },
            },
            levels = { 250, 320, 330, 340 },
        },
    },
    [260] = {
        {
            spell_id = 23129,
            name = "World Enlarger",
            icon = "inv_misc_enggizmos_08",
            source = {
                type = "Item",
                recipe_item_ids = { 18661 },
            },
            product = { item_id = 18660, qty = 1 },
            materials = {
                { item_id = 10561, qty = 1 },
                { item_id = 15994, qty = 2 },
                { item_id = 10558, qty = 1 },
                { item_id = 10560, qty = 1 },
                { item_id = 3864, qty = 1 },
            },
            levels = { 260, 260, 265, 270 },
        },
        {
            spell_id = 23071,
            name = "Truesilver Transformer",
            icon = "inv_staff_18",
            source = {
                type = "Item",
                recipe_item_ids = { 18651 },
            },
            product = { item_id = 18631, qty = 1 },
            materials = {
                { item_id = 6037, qty = 2 },
                { item_id = 7067, qty = 2 },
                { item_id = 7069, qty = 1 },
            },
            levels = { 260, 270, 275, 280 },
        },
        {
            spell_id = 23077,
            name = "Gyrofreeze Ice Reflector",
            icon = "inv_misc_enggizmos_02",
            source = {
                type = "Item",
                recipe_item_ids = { 18652 },
            },
            product = { item_id = 18634, qty = 1 },
            materials = {
                { item_id = 15994, qty = 6 },
                { item_id = 18631, qty = 2 },
                { item_id = 12361, qty = 2 },
                { item_id = 7078, qty = 4 },
                { item_id = 3829, qty = 2 },
                { item_id = 13467, qty = 4 },
            },
            levels = { 260, 280, 290, 300 },
        },
        {
            spell_id = 19792,
            name = "Thorium Rifle",
            icon = "inv_weapon_rifle_07",
            source = {
                type = "Item",
                recipe_item_ids = { 16043 },
            },
            product = { item_id = 15995, qty = 1 },
            materials = {
                { item_id = 10559, qty = 2 },
                { item_id = 10561, qty = 2 },
                { item_id = 15994, qty = 2 },
                { item_id = 12359, qty = 4 },
                { item_id = 10546, qty = 1 },
            },
            levels = { 260, 280, 290, 300 },
        },
        {
            spell_id = 19790,
            name = "Thorium Grenade",
            icon = "inv_misc_bomb_08",
            source = {
                type = "Item",
                recipe_item_ids = { 16041 },
            },
            product = { item_id = 15993, qty = 3 },
            materials = {
                { item_id = 15994, qty = 1 },
                { item_id = 12359, qty = 3 },
                { item_id = 15992, qty = 3 },
                { item_id = 14047, qty = 3 },
            },
            levels = { 260, 280, 290, 300 },
        },
        {
            spell_id = 19791,
            name = "Thorium Widget",
            icon = "inv_gizmo_04",
            source = {
                type = "Item",
                recipe_item_ids = { 16042 },
            },
            product = { item_id = 15994, qty = 1 },
            materials = {
                { item_id = 12359, qty = 3 },
                { item_id = 14047, qty = 1 },
            },
            levels = { 260, 280, 290, 300 },
        },
    },
    [265] = {
        {
            spell_id = 23096,
            name = "Alarm-O-Bot",
            icon = "inv_misc_enggizmos_13",
            source = {
                type = "Item",
                recipe_item_ids = { 18654 },
            },
            product = { item_id = 18645, qty = 1 },
            materials = {
                { item_id = 12359, qty = 4 },
                { item_id = 15994, qty = 2 },
                { item_id = 8170, qty = 4 },
                { item_id = 7910, qty = 1 },
                { item_id = 7191, qty = 1 },
            },
            levels = { 265, 275, 280, 285 },
        },
        {
            spell_id = 23078,
            name = "Goblin Jumper Cables XL",
            icon = "inv_misc_enggizmos_11",
            source = {
                type = "Item",
                recipe_item_ids = { 18653 },
            },
            product = { item_id = 18587, qty = 1 },
            materials = {
                { item_id = 15994, qty = 2 },
                { item_id = 18631, qty = 2 },
                { item_id = 7191, qty = 2 },
                { item_id = 14227, qty = 2 },
                { item_id = 7910, qty = 2 },
            },
            levels = { 265, 285, 295, 305 },
        },
        {
            spell_id = 19793,
            name = "Lifelike Mechanical Toad",
            icon = "inv_misc_monsterhead_03",
            source = {
                type = "Item",
                recipe_item_ids = { 16044 },
            },
            product = { item_id = 15996, qty = 1 },
            materials = {
                { item_id = 12803, qty = 1 },
                { item_id = 15994, qty = 4 },
                { item_id = 10558, qty = 1 },
                { item_id = 8170, qty = 1 },
            },
            levels = { 265, 285, 295, 305 },
        },
    },
    [270] = {
        {
            spell_id = 19794,
            name = "Spellpower Goggles Xtreme Plus",
            icon = "inv_helmet_47",
            source = {
                type = "Item",
                recipe_item_ids = { 16045 },
            },
            product = { item_id = 15999, qty = 1 },
            materials = {
                { item_id = 10502, qty = 1 },
                { item_id = 7910, qty = 4 },
                { item_id = 12810, qty = 2 },
                { item_id = 14047, qty = 8 },
            },
            levels = { 270, 290, 300, 310 },
        },
    },
    [275] = {
        {
            spell_id = 26426,
            name = "Large Blue Rocket Cluster",
            icon = "inv_misc_missilelargecluster_blue",
            source = {
                type = "Item",
                recipe_item_ids = { 21733 },
            },
            product = { item_id = 21714, qty = 3 },
            materials = {
                { item_id = 15992, qty = 1 },
                { item_id = 8170, qty = 1 },
            },
            levels = { 275, 275, 280, 285 },
        },
        {
            spell_id = 26427,
            name = "Large Green Rocket Cluster",
            icon = "inv_misc_missilelargecluster_green",
            source = {
                type = "Item",
                recipe_item_ids = { 21734 },
            },
            product = { item_id = 21716, qty = 3 },
            materials = {
                { item_id = 15992, qty = 1 },
                { item_id = 8170, qty = 1 },
            },
            levels = { 275, 275, 280, 285 },
        },
        {
            spell_id = 26428,
            name = "Large Red Rocket Cluster",
            icon = "inv_misc_missilelargecluster_red",
            source = {
                type = "Item",
                recipe_item_ids = { 21735 },
            },
            product = { item_id = 21718, qty = 3 },
            materials = {
                { item_id = 15992, qty = 1 },
                { item_id = 8170, qty = 1 },
            },
            levels = { 275, 275, 280, 285 },
        },
        {
            spell_id = 23080,
            name = "Powerful Seaforium Charge",
            icon = "spell_shadow_detectinvisibility",
            source = {
                type = "Item",
                recipe_item_ids = { 18656 },
            },
            product = { item_id = 18594, qty = 1 },
            materials = {
                { item_id = 15994, qty = 2 },
                { item_id = 15992, qty = 3 },
                { item_id = 8170, qty = 2 },
                { item_id = 159, qty = 1 },
            },
            levels = { 275, 275, 285, 295 },
        },
        {
            spell_id = 23079,
            name = "Major Recombobulator",
            icon = "inv_misc_enggizmos_09",
            source = {
                type = "Item",
                recipe_item_ids = { 18655 },
            },
            product = { item_id = 18637, qty = 1 },
            materials = {
                { item_id = 16000, qty = 2 },
                { item_id = 18631, qty = 1 },
                { item_id = 14047, qty = 2 },
            },
            levels = { 275, 285, 290, 295 },
        },
        {
            spell_id = 19796,
            name = "Dark Iron Rifle",
            icon = "inv_weapon_rifle_08",
            source = {
                type = "Item",
                recipe_item_ids = { 16048 },
            },
            product = { item_id = 16004, qty = 1 },
            materials = {
                { item_id = 16000, qty = 2 },
                { item_id = 11371, qty = 6 },
                { item_id = 10546, qty = 2 },
                { item_id = 12361, qty = 2 },
                { item_id = 12799, qty = 2 },
                { item_id = 8170, qty = 4 },
            },
            levels = { 275, 295, 305, 315 },
        },
        {
            spell_id = 26443,
            name = "Firework Cluster Launcher",
            icon = "inv_misc_enggizmos_03",
            source = {
                type = "Item",
                recipe_item_ids = { 21737 },
            },
            product = { item_id = 21570, qty = 1 },
            materials = {
                { item_id = 9060, qty = 4 },
                { item_id = 9061, qty = 4 },
                { item_id = 18631, qty = 2 },
                { item_id = 10561, qty = 1 },
            },
            levels = { 275, 295, 305, 315 },
        },
        {
            spell_id = 19814,
            name = "Masterwork Target Dummy",
            icon = "inv_crate_02",
            source = {
                type = "Item",
                recipe_item_ids = { 16046 },
            },
            product = { item_id = 16023, qty = 1 },
            materials = {
                { item_id = 10561, qty = 1 },
                { item_id = 16000, qty = 1 },
                { item_id = 15994, qty = 2 },
                { item_id = 6037, qty = 1 },
                { item_id = 8170, qty = 2 },
                { item_id = 14047, qty = 4 },
            },
            levels = { 275, 295, 305, 315 },
        },
        {
            spell_id = 28327,
            name = "Steam Tonk Controller",
            icon = "inv_misc_enggizmos_20",
            source = {
                type = "Trainer",
            },
            product = { item_id = 22728, qty = 1 },
            materials = {
                { item_id = 15994, qty = 2 },
                { item_id = 10561, qty = 1 },
                { item_id = 10558, qty = 1 },
            },
            levels = { 275, 295, 305, 315 },
        },
        {
            spell_id = 19795,
            name = "Thorium Tube",
            icon = "inv_gizmo_pipe_04",
            source = {
                type = "Item",
                recipe_item_ids = { 16047 },
            },
            product = { item_id = 16000, qty = 1 },
            materials = {
                { item_id = 12359, qty = 6 },
            },
            levels = { 275, 295, 305, 315 },
        },
    },
    [285] = {
        {
            spell_id = 19800,
            name = "Thorium Shells",
            icon = "inv_ammo_bullet_03",
            source = {
                type = "Item",
                recipe_item_ids = { 16051 },
            },
            product = { item_id = 15997, qty = 200 },
            materials = {
                { item_id = 12359, qty = 2 },
                { item_id = 15992, qty = 1 },
            },
            levels = { 285, 305, 315, 325 },
        },
        {
            spell_id = 19799,
            name = "Dark Iron Bomb",
            icon = "inv_misc_bomb_05",
            source = {
                type = "Item",
                recipe_item_ids = { 16049 },
            },
            product = { item_id = 16005, qty = 3 },
            materials = {
                { item_id = 15994, qty = 2 },
                { item_id = 11371, qty = 1 },
                { item_id = 15992, qty = 3 },
                { item_id = 14047, qty = 3 },
            },
            levels = { 285, 305, 315, 325 },
        },
        {
            spell_id = 19815,
            name = "Delicate Arcanite Converter",
            icon = "inv_gizmo_07",
            source = {
                type = "Item",
                recipe_item_ids = { 16050 },
            },
            product = { item_id = 16006, qty = 1 },
            materials = {
                { item_id = 12360, qty = 1 },
                { item_id = 14227, qty = 1 },
            },
            levels = { 285, 305, 315, 325 },
        },
        {
            spell_id = 23486,
            name = "Dimensional Ripper - Everlook",
            icon = "inv_misc_enggizmos_07",
            source = {
                type = "Trainer",
            },
            product = { item_id = 18984, qty = 1 },
            materials = {
                { item_id = 3860, qty = 10 },
                { item_id = 18631, qty = 1 },
                { item_id = 7077, qty = 4 },
                { item_id = 7910, qty = 2 },
                { item_id = 10586, qty = 1 },
            },
            levels = { 260, 285, 295, 305 },
        },
        {
            spell_id = 23489,
            name = "Ultrasafe Transporter - Gadgetzan",
            icon = "inv_misc_enggizmos_12",
            source = {
                type = "Trainer",
            },
            product = { item_id = 18986, qty = 1 },
            materials = {
                { item_id = 3860, qty = 12 },
                { item_id = 18631, qty = 2 },
                { item_id = 7075, qty = 4 },
                { item_id = 7079, qty = 2 },
                { item_id = 7909, qty = 4 },
                { item_id = 9060, qty = 1 },
            },
            levels = { 260, 285, 295, 305 },
        },
    },
    [290] = {
        {
            spell_id = 23081,
            name = "Hyper-Radiant Flame Reflector",
            icon = "inv_misc_enggizmos_04",
            source = {
                type = "Item",
                recipe_item_ids = { 18657 },
            },
            product = { item_id = 18638, qty = 1 },
            materials = {
                { item_id = 11371, qty = 4 },
                { item_id = 18631, qty = 3 },
                { item_id = 7080, qty = 6 },
                { item_id = 7910, qty = 4 },
                { item_id = 12800, qty = 2 },
            },
            levels = { 290, 310, 320, 330 },
        },
        {
            spell_id = 19825,
            name = "Master Engineer's Goggles",
            icon = "inv_helmet_47",
            source = {
                type = "Item",
                recipe_item_ids = { 16053 },
            },
            product = { item_id = 16008, qty = 1 },
            materials = {
                { item_id = 10500, qty = 1 },
                { item_id = 12364, qty = 2 },
                { item_id = 12810, qty = 4 },
            },
            levels = { 290, 310, 320, 330 },
        },
        {
            spell_id = 19819,
            name = "Voice Amplification Modulator",
            icon = "inv_jewelry_amulet_07",
            source = {
                type = "Item",
                recipe_item_ids = { 16052 },
            },
            product = { item_id = 16009, qty = 1 },
            materials = {
                { item_id = 16006, qty = 2 },
                { item_id = 10558, qty = 1 },
                { item_id = 15994, qty = 1 },
                { item_id = 12799, qty = 1 },
            },
            levels = { 290, 310, 320, 330 },
        },
    },
    [300] = {
        {
            spell_id = 22795,
            name = "Core Marksman Rifle",
            icon = "inv_weapon_rifle_05",
            source = {
                type = "Item",
                recipe_item_ids = { 18292 },
            },
            product = { item_id = 18282, qty = 1 },
            materials = {
                { item_id = 17010, qty = 4 },
                { item_id = 17011, qty = 2 },
                { item_id = 12360, qty = 6 },
                { item_id = 16006, qty = 2 },
                { item_id = 16000, qty = 2 },
            },
            levels = { 300, 320, 330, 340 },
        },
        {
            spell_id = 22797,
            name = "Force Reactive Disk",
            icon = "spell_arcane_portaldarnassus",
            source = {
                type = "Item",
                recipe_item_ids = { 18291 },
            },
            product = { item_id = 18168, qty = 1 },
            materials = {
                { item_id = 12360, qty = 6 },
                { item_id = 16006, qty = 2 },
                { item_id = 7082, qty = 8 },
                { item_id = 12803, qty = 12 },
                { item_id = 7076, qty = 8 },
            },
            levels = { 300, 320, 330, 340 },
        },
        {
            spell_id = 19830,
            name = "Arcanite Dragonling",
            icon = "inv_misc_head_dragon_01",
            source = {
                type = "Item",
                recipe_item_ids = { 16054 },
            },
            product = { item_id = 16022, qty = 1 },
            materials = {
                { item_id = 10576, qty = 1 },
                { item_id = 16006, qty = 8 },
                { item_id = 12655, qty = 10 },
                { item_id = 15994, qty = 6 },
                { item_id = 10558, qty = 4 },
                { item_id = 12810, qty = 6 },
            },
            levels = { 300, 320, 330, 340 },
        },
        {
            spell_id = 22793,
            name = "Biznicks 247x128 Accurascope",
            icon = "inv_misc_spyglass_02",
            source = {
                type = "Item",
                recipe_item_ids = { 18290 },
            },
            product = { item_id = 18283, qty = 1 },
            materials = {
                { item_id = 17011, qty = 2 },
                { item_id = 7076, qty = 2 },
                { item_id = 16006, qty = 4 },
                { item_id = 11371, qty = 6 },
                { item_id = 16000, qty = 1 },
            },
            levels = { 300, 320, 330, 340 },
        },
        {
            spell_id = 24356,
            name = "Bloodvine Goggles",
            icon = "inv_helmet_47",
            source = {
                type = "Item",
                recipe_item_ids = { 20000 },
            },
            product = { item_id = 19999, qty = 1 },
            materials = {
                { item_id = 19726, qty = 4 },
                { item_id = 19774, qty = 5 },
                { item_id = 16006, qty = 2 },
                { item_id = 12804, qty = 8 },
                { item_id = 12810, qty = 4 },
            },
            levels = { 300, 320, 330, 340 },
        },
        {
            spell_id = 24357,
            name = "Bloodvine Lens",
            icon = "inv_helmet_44",
            source = {
                type = "Item",
                recipe_item_ids = { 20001 },
            },
            product = { item_id = 19998, qty = 1 },
            materials = {
                { item_id = 19726, qty = 5 },
                { item_id = 19774, qty = 5 },
                { item_id = 16006, qty = 1 },
                { item_id = 12804, qty = 8 },
                { item_id = 12810, qty = 4 },
            },
            levels = { 300, 320, 330, 340 },
        },
        {
            spell_id = 19833,
            name = "Flawless Arcanite Rifle",
            icon = "inv_weapon_rifle_03",
            source = {
                type = "Item",
                recipe_item_ids = { 16056 },
            },
            product = { item_id = 16007, qty = 1 },
            materials = {
                { item_id = 12360, qty = 10 },
                { item_id = 16000, qty = 2 },
                { item_id = 7078, qty = 2 },
                { item_id = 7076, qty = 2 },
                { item_id = 12800, qty = 2 },
                { item_id = 12810, qty = 2 },
            },
            levels = { 300, 320, 330, 340 },
        },
        {
            spell_id = 23082,
            name = "Ultra-Flash Shadow Reflector",
            icon = "inv_misc_enggizmos_16",
            source = {
                type = "Item",
                recipe_item_ids = { 18658 },
            },
            product = { item_id = 18639, qty = 1 },
            materials = {
                { item_id = 11371, qty = 8 },
                { item_id = 18631, qty = 4 },
                { item_id = 12803, qty = 6 },
                { item_id = 12808, qty = 4 },
                { item_id = 12800, qty = 2 },
                { item_id = 12799, qty = 2 },
            },
            levels = { 300, 320, 330, 340 },
        },
        {
            spell_id = 19831,
            name = "Arcane Bomb",
            icon = "spell_shadow_mindbomb",
            source = {
                type = "Item",
                recipe_item_ids = { 16055 },
            },
            product = { item_id = 16040, qty = 3 },
            materials = {
                { item_id = 16006, qty = 1 },
                { item_id = 12359, qty = 3 },
                { item_id = 14047, qty = 1 },
            },
            levels = { 300, 320, 330, 340 },
        },
        {
            spell_id = 22704,
            name = "Field Repair Bot 74A",
            icon = "inv_egg_05",
            source = {
                type = "Item",
                recipe_item_ids = { 18235 },
            },
            product = { item_id = 18232, qty = 1 },
            materials = {
                { item_id = 12359, qty = 12 },
                { item_id = 8170, qty = 4 },
                { item_id = 7191, qty = 1 },
                { item_id = 7067, qty = 2 },
                { item_id = 7068, qty = 1 },
            },
            levels = { 300, 320, 330, 340 },
        },
    },
}
